### ISSUE TITLE
Initializing the model with the previous population?

### ISSUE THREAD

**Issue by vperic** [trevorstephens/gplearn#10]
I'm using the SymbolicRegressor class to iteratively train models on some data (for use as a surrogate model, actually). Is there a way to reuse the last generation of a previous model as the initial population of a new model? Ideally, something like "half new, half old", so I could still get new models as well.

**Comment by trevorstephens** [comment]
So kind of like a "warm-start" to add extra generations after an initial training? Seems like a viable idea. It is not possible in the package currently, I can implement it for the next release though.

**Comment by vperic** [comment]
Great! I'm currently using gplearn as part of a project with a rapidly approaching deadline - is there maybe a hack you could provide with this feature? I haven't looked at the code myself, perhaps it's not hard to do if you could give me some advice. Thanks!

**Comment by trevorstephens** [comment]
You could look at the code for `sklearn.ensemble.RandomForestClassifier` which has a `warm_start` parameter for ideas. It's not entirely trivial though I'm afraid, ie. no "hack" available without some coding. PR welcome.
