### ISSUE TITLE
Transformer creates duplicate features in best_programs

### ISSUE THREAD

**Issue by hubrix** [trevorstephens/gplearn#102]
I end up with stuff like this

'add(X13, X70)'
'add(X13, add(X13, X70))'
'add(add(X13, X70), X70)'
'add(X13, X70)'
'add(X13, X70)'
'add(X13, X70)'

**Comment by trevorstephens** [comment]
Try increasing the population size and reducing the tournament size. Looks like your population is getting dominated by only a few individual programs. Might also try reducing parsimony as it is obviously favouring very small solutions which might be forcing only a very few tiny solutions that are OK to win everything.

**Comment by riddle6666** [comment]
Can we drop duplicated _Program which has the same program in the script itself?
