### ISSUE TITLE
Symbolic Regressor for multiple lists of measured data

### ISSUE THREAD

**Issue by AnaKolody** [trevorstephens/gplearn#103]
I am currently using GP learn to find a model from measured data. 
My model should depend on three variables. Each variable would be a list of measured data or measuring parameters as the 'X input' for the Symbolic Regressor. The 'Y input' would also be a list of measured data. 
In the picture below you can see the measured data. Each curve represents one measured X and Y. The behaviour of each curve also depends on two other variables (theta and phi).
![image](https://user-images.githubusercontent.com/43571711/46010234-33337980-c0c2-11e8-813f-e3b49fe4259b.png)
I can already find a function for each list of measured data i.e. each curve. Is it possible for the SymbolicRegressor to find one single function for all curves? If yes, how would the input for the Symbolic Regressor be like?

**Comment by trevorstephens** [comment]
Maybe create a couple of columns for the two variables and create a hyperplane. No idea if it will be useful in that form for you though.
