### ISSUE TITLE
self defined function raise Error

### ISSUE THREAD

**Issue by isaac-you** [trevorstephens/gplearn#105]
def ma(x,n):
	xLen = len(x)
	xMA = np.zeros(xLen)
	for i in range(n,xLen+1):
		xMA[i-1] = np.mean(x[i-n:i])
	return xMA

MovingAverage = make_function(function=ma,
                        name='MovingAverage',
                        arity=2)

TypeError                                 Traceback (most recent call last)
<ipython-input-69-49aaa837b2f7> in <module>()
      1 MovingAverage = make_function(function=ma,
      2                         name='MovingAverage',
----> 3                         arity=2)
      4 MovingMax = make_function(function=maxn,
      5                         name='MovingMax',
TypeError: only integer scalar arrays can be converted to a scalar index

First of all, GPlearn is a wonderful package to do the symbolic regression. But when I want to study time series and generate some expressions about time series, some problem exits. 
I defined my own moving average function, but GPlearn will raise the Error, can you give me some advice?

**Comment by trevorstephens** [comment]
The arguments to the function are arrays of the length of your dataset, ie the features. It looks like you are wanting to pass an integer and have that "tuned" ... This is not supported.

**Comment by trevorstephens** [comment]
See here for example use: https://gplearn.readthedocs.io/en/stable/advanced.html#custom-functions

**Comment by isaac-you** [comment]
Thank you for your quick reply.  Actually my question is that can I define a function which can calculate the time series data? and determine the parameter by gplearn.  For example, 1. avg(p; n): average of price or volume over the past n days;  2. max(p; n): maximum value of price or volume over the past n days;  3. min(p; n): minimum value of price or volume over the past n days. 
And many genetic programming tools can just output simple functions which only include：+ - * / exp log sin cos etc. The final output expressions like : 3x + 2y^2 + sin(z) .
And in finance or time series problems, we usually want to output some functions like : 
          3*avg(p; n) + 8*max(p; n)^2,
 in which p is the price of stock, n is the past days .  These output expressions contain avg(p; n), max(p; n), min(p; n),  in which p is the terminal input data  and GP can determine the parameter n.  

I think GPlearn can really do the job,  but  I don't know how to define the functions like avg(p; n), max(p; n), min(p; n)  in GPlearn. 

Can you give me some advice? Thank you so much.

**Comment by trevorstephens** [comment]
So if you want `n` to be flexible, it would have to be calculated along the lines of:

    def my_func(x1, x2):
        n = int(mean(x2))
        return some_ts_function(x1, n)

Note that `x2` here can be either a column from your data, a vector of constants, or the combination of any mathematical magic that occurred further down the function tree.

Otherwise, if it is ok to have `n` fixed by you at the beginning, something like this should be ok:

    def my_func(x1):
        n = 4
        return some_ts_function(x1, n)

Either way, currently `gplearn` doesn't support having a flexible input such as what it looks like you are wishing to achieve with the `n` input to your function, or any way to force the input of a function to be of a specific form.

Also note that all outputs of the function must be finite, so you may need to pad the leading NaN's if your time series function creates any.

Let me know if anything is unclear.

**Comment by isaac-you** [comment]
Thank you for your advice.
           I think it is a good idea to select a proper N from a range ,such as : [1,2,3,4,5,10,15,30,60,120,180,250...].  And these lag N days range are usually used by financial problems.  So there is no need to get a totally flexible N. And then I can make the N range as a  column from the data, a vector of constants. 
            But still I have problems of coding:

def sma4(x,n):
	x = np.array(x)
	n = int(np.mean(n))
	weights = np.ones(n)/n
	return np.convolve(a=weights,v=x,mode='valid')

in the function above , if I use "n = int(n)" or "n = np.mean(int(n))" then I will get an Error:  "TypeError: only size-1 arrays can be converted to Python scalars"
 if I use "n = int(np.mean(n))" , then it is OK for this line , but still for the last line, I get an Error "ValueError: v cannot be empty"  when I use make_function() ： 

MovingAverage = make_function(function=sma4,
                        name='MovingAverage',
                        arity=2)

<ipython-input-34-0b4dd67eb4ed> in <module>()
      1 MovingAverage = make_function(function=sma4,
      2                         name='MovingAverage',
----> 3                         arity=2)

Maybe this is a newbie questions about datatype in python.  So it is a little annoying for you.  
Thank you for your advice : )
