### ISSUE TITLE
self defined function raise Error _version2

### ISSUE THREAD

**Issue by isaac-you** [trevorstephens/gplearn#106]
def sma(x,n):
	weights = np.ones(n)/n
	smaX = np.convolve(weights,x)
	return smaX[:-n+1]

MovingAverage = make_function(function=sma,
                        name='MovingAverage',
                        arity=2)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-104-056caf2629ab> in <module>()
      1 MovingAverage = make_function(function=sma,
      2                         name='MovingAverage',
----> 3                         arity=2)

<ipython-input-103-560e2cc39431> in sma(x, n)
      1 def sma(x,n):
----> 2         weights = np.ones(n)/n
      3         smaX = np.convolve(weights,x)
      4         return smaX[:-n+1]

~/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py in ones(shape, dtype, order)
    186 
    187     """
--> 188     a = empty(shape, dtype, order)
    189     multiarray.copyto(a, 1, casting='unsafe')
    190     return a

TypeError: 'numpy.float64' object cannot be interpreted as an integer

I change another moving average function, but still raise Error
I defined my own moving average function, but GPlearn will raise the Error, can you give me some advice?

**Comment by trevorstephens** [comment]
Please do not duplicate issues.

**Comment by isaac-you** [comment]
Thank you for your quick reply. And I won't duplicate issues again.
