### ISSUE TITLE
sklearn seems to be devendoring joblib

### ISSUE THREAD

**Issue by trevorstephens** [trevorstephens/gplearn#114]
Some related issues in sklearn:

https://github.com/scikit-learn/scikit-learn/pull/11166
https://github.com/scikit-learn/scikit-learn/pull/11471
https://github.com/scikit-learn/scikit-learn/pull/12345
https://github.com/scikit-learn/scikit-learn/issues/12447

Need to keep an eye on this one as we rely on the bundled joblib here.

**Comment by jnothman** [comment]
I think we will deprecate the sklearn.externals.joblib import, but keep it available. Same may be true of sklearn.utils.{parallel_backend,register_parallel_backend}

**Comment by trevorstephens** [comment]
Thanks @jnothman 

https://github.com/scikit-learn/scikit-learn/pull/13531 removed this. Will need to do a release to put a dependency on joblib.

**Comment by trevorstephens** [comment]
To think over.... Maybe do an import warning for joblib rather than dependency? We already have problems with parallel being slow for small populations/programs #71 

    import warnings
    try:
        import joblib stuff
    except ImportError:
        warnings.warn('parallel needs joblib installed, pip install joblib yada yada', ImportWarning)
