### ISSUE TITLE
Should I pull request my geometric mutation/crossover?

### ISSUE THREAD

**Issue by DaGuT** [trevorstephens/gplearn#121]
Hello,

I've added https://github.com/DaGuT/gplearn/commit/1bc6d9e0c6106327f67a3a39d3b91a552a181432 here geometric semantic mutations and crossover as well as elitism. It works fine.

The question is, should I properly document it (and refactor a little bit so it will be less human dependant) and make a pull request or you dont need it and I'll just keep it for myself?

You'll see some lists there or 'random' which only returns 1. I did that on purpose to check everything and compare. That's why I'm asking. If you dont need it, I'll just keep as it is now.

**Comment by trevorstephens** [comment]
Hey @DaGuT , I'm not familiar with this method, do you have some background on it? Article or research paper I can look at?

**Comment by trevorstephens** [comment]
ie. Be good to understand what this improves, changes, etc, over the standard evolutionary processes.

**Comment by DaGuT** [comment]
https://link.springer.com/chapter/10.1007/978-3-642-32937-1_3
Not sure I can upload paper here.
But I was developing according to this work ( https://www.researchgate.net/publication/312000655_An_Introduction_to_Geometric_Semantic_Genetic_Programming ) and in contact directly with author :)
