### ISSUE TITLE
My version of gplearn (NewMath gplearn)

### ISSUE THREAD

**Issue by ghost** [trevorstephens/gplearn#122]
Hello, my version of gplearn is good for made easy GP, convert indiv program to LaTeX, and this with more math functions. ;)
Enjoy !
[https://github.com/LaGvidilo/gplearn](https://github.com/LaGvidilo/gplearn)

**Comment by LaGvidilo** [comment]
Now I develop an project based on your repository, you have a best GP tech ever.
Good job ! but I think you can be add more functions :)
You see or not ? You have a tool for make greats mathematics in semi-auto mode.
GPLearn is an weapon ! Look my proto-interface, just enter params, name file input and that turn !
If you visit wikipedia French in section StarTrek Moteur a distortion (Warp) : you can look formulas resulted by my fork.
But I don't give this initiative without your implementation.
So, thank you.

Best regards,
LaGvidilo(Alias Rick).

**Comment by LaGvidilo** [comment]
Hello i have updated my version for python3 !
I have an bug of zero divide, next step is fix that.
(You can use fast with import simple:
```
import gplearn.GPTool as gp
```
)

Best regards,
LaGvidilo(Alias Rick).
