### ISSUE TITLE
Saving with best fitness??

### ISSUE THREAD

**Issue by devilishj** [trevorstephens/gplearn#128]
GREAT WORK!!!  Had an issue but of course I figured it out right after posting here, lol.

**Comment by trevorstephens** [comment]
That's the way it goes :)

Is there something that could be clearer in the docs?

**Comment by devilishj** [comment]
It was all me! I was doing a quick pickle test and though there was an issue with saving the fitness, but I had the pre-pickle prediction indexed to datetime, and the post-pickle wasn't... That's why they looked so different.  I've been struggling to get algorithms to really catch the mathematical relationships that I know exist in my features... Gplearn is so good at this!!!!
________________________________
