### ISSUE TITLE
Dimensional correctness

### ISSUE THREAD

**Issue by slavust** [trevorstephens/gplearn#132]
I'm considering implementing dimensional analysis for symbolic regression to make regression faster. See [Wikipedia: dimensional analysis](https://en.wikipedia.org/wiki/Dimensional_analysis) Also, in my project I try to implement regression based on partially known data and dimensional analysis can help drop some unsuitable solutions by generating only dimensionally correct ones. I'm only starting investigation but need to place results (in case of success) somewhere it might be supported and I'd like to make prototype in library which will probably accept the final results. Can I expect that such feature might be accepted and placed to gplearn?

**Comment by trevorstephens** [comment]
Hi @slavust ... The package is open source. You can modify it and do whatever you like with the code in your own branch. I cannot guarantee that some future change that you make will be merged unfortunately though. Especially when I don't really know what that change will be.
