### ISSUE TITLE
No module named 'gplearn'

### ISSUE THREAD

**Issue by Payam-Ebadi** [trevorstephens/gplearn#134]
My machine has windows 10 64-bit installed on it, I recently downloaded python 3.7 and the latest version of Anaconda which was registered on python.
I installed gplearn via pip and wanted to run the example for SymbolicTransformer on Jupiter Notebook, But I have this error: No module named 'gplearn'
Does anybody know how to solve the issue???

**Comment by trevorstephens** [comment]
Not sure that I understand what you mean by registering anaconda on python...

Anyhow, at the terminal immediately before you launch your notebook, is `gplearn` shown when running `conda list`?

**Comment by Payam-Ebadi** [comment]
no I can NOT find the gplearn package in conda list to add it to my environment, while I installed the gplearn package via pip install on my machine!!!

**Comment by trevorstephens** [comment]
It is possible that you have multiple python environments up, perhaps you have both a system python and an anaconda bundled python. I would suggest first trying to reinstall gplearn before you launch jupyter.

If that doesn't work then you could investigate using a virtual environment to isolate all the python and package versions. There are lots of guides online for this, search for one using anaconda under Windows.
