### ISSUE TITLE
feature_names Parameter Not Working

### ISSUE THREAD

**Issue by gfleetwood** [trevorstephens/gplearn#148]
Hi,

I'm trying to pass the exact feature names to the feature_names parameter for the Symbolic Regressor but I'm getting this error:

```
TypeError: __init__() got an unexpected keyword argument 'feature_names'
```

On a related note, should I assume that X0, X1, X2, ... correspond to my first feature, second feature and so on?

On an unrelated note, I'm guessing there's no cross validation going on under the hood?

**Comment by trevorstephens** [comment]
What version of gplearn are you using? `pip freeze` in console or `gplearn.__version__` in python will tell you. This feature is not in a pypi release yet. Hopefully in a week or two I will release 0.4.0. In the meantime you need to install the package from the git source code to get this feature.

Yes, the numbers represent the index of the feature.

There is no cross validation built-in. You can use scikit-learn tooling to do this, just like any other scikit-learn estimator.

**Comment by gfleetwood** [comment]
I used pip to install the package so that explains it. Thanks.
