### ISSUE TITLE
Custom function enhancement

### ISSUE THREAD

**Issue by Alsac** [trevorstephens/gplearn#173]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by trevorstephens** [comment]
Looks like this was opened by accident, closing. Reopen if you have some more details :smiley:

**Comment by Alsac** [comment]
Thank u for solving parallel process matter! Now I face a tough problem.When I use custom functions of arity=1, sometime I want it works in different sample groups respectively, which works just like pd.groupby(as_index=True).apply(lambda x:x.rank(axis=0)). even though using numpy_indexed package, I can let ndarray data groupby by certain column and then use function(e.g np.argsort), the custom function seems not receipt data with keys(using for groupby e.g date series). So I am wondering if genetic module could receipt ndarray data with groupby index then we can do groupby operation as long as the data shape unchanged.

**Comment by Alsac** [comment]
OK! I'll open another request.

**Comment by trevorstephens** [comment]
I have no plans to support this. You may be able to solve it by hard-coding indexes into your custom functions but this is too difficult a thing to make generally available or useful.

**Comment by Alsac** [comment]
😂yes it is pretty difficult.. But it's important in my current program project, I will try this,thank you!😊

**Comment by Alsac** [comment]
😂yes it is pretty difficult.. But it's important in my current program project, I will try this,thank you!😊

**Comment by trevorstephens** [comment]
good luck @Alsac
