### ISSUE TITLE
I can't import SymbolicClassifier, It's ImportError. What should I do

### ISSUE THREAD

**Issue by Eddy8888** [trevorstephens/gplearn#176]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

[](url)

**Comment by trevorstephens** [comment]
Please open a BUG report issue and follow the instructions.

**Comment by Eddy8888** [comment]
I mean from your Ex.4 Classification. It's ImportError name SymbolicClassifier

**Comment by trevorstephens** [comment]
I can't help you unless you open a BUG report issue and follow the instructions. Those instructions tell me about your system so I can have any chance of knowing why you have an error. So... please open a new bug report and follow the instructions
