### ISSUE TITLE
Stopping criteria seems to depend on total error?  Can we make it stop based on median error?

### ISSUE THREAD

**Issue by rfox12** [trevorstephens/gplearn#182]
For very large data sets I've noticed my runs never stop.  And as far as I can tell it's because aggregate error is being taken into account?  (Not sure on this).  Here is a sample program... at 5 generations it gets to the correct answer of 1.200... but by default it will run all they way to 15 generations.  

rng = check_random_state(0)

# Training samples
X_train = rng.uniform(10000, 50000, 10000).reshape(5000, 2)
y_train = X_train[:, 0]*1.2

est_gp = SymbolicRegressor(population_size=5000,
                           const_range=(-1.0, 2.0),
                           function_set=['mul'],
                           generations=20, stopping_criteria=5,
                            p_crossover=0.2, p_subtree_mutation=0.1,
                            p_hoist_mutation=0.05, p_point_mutation=0.5,
                           max_samples=0.9, verbose=1,
                           parsimony_coefficient=100, random_state=0)
est_gp.fit(X_train, y_train)

**Comment by trevorstephens** [comment]
@rfox12 the evolution will stop when the fitness of the best individual in the population drops below your threshold of `stopping_criteria=5`. In your example this happens at gen 15 where it drops to 3.77 and is based by default on mean absolute error. I'm not sure what you mean by it being "correct" at generation 5.

You can certainly define your own fitness metric if you want to work with the median error. This sounds slightly unusual to me, but see these links for how to do it: 

https://gplearn.readthedocs.io/en/stable/reference.html#user-defined-fitness-metrics
https://gplearn.readthedocs.io/en/stable/advanced.html#custom-fitness
https://github.com/trevorstephens/gplearn/blob/master/gplearn/fitness.py#L125

**Comment by rfox12** [comment]
Thanks for the reply!  Love gplearn so far. All I mean is that if you change the generations parameter to 5 in the code above you get the exact same output as the 15 generation version "print(est_gp._program):"  mul(X0, 1.200)

So are there really small decimals at play here?  Just from an output perspective it seems we got to the answer at 5 generations.

**Comment by trevorstephens** [comment]
Glad you're enjoying it 😄 

I see what you mean. Yes just rounding off the floating point numbers in this example. You can peek into the undocumented internal representation to see the floats are not quite 1.2 using `print(est_gp._program.program)`

**Comment by HuangHam** [comment]
I run into the same problem where I set stopping_criteria=10^-5 but it doesn't stop even tho the error is already as low as 1.8602e-08 as indicated by the verbose report.
