### ISSUE TITLE
Custom Function With A Random Number Input

### ISSUE THREAD

**Issue by Gaiss** [trevorstephens/gplearn#184]
Hi, I want to define a custom function like `ts_mean(X,d)` where `X` is an array and `d` is a random integer to calculate the mean of the last d number of X. However the example given in the document only introduce the situation where all the input are arrays from the data set. Could you please tell me how to let it know I want it to produce a number as input for me?

In an example of SymbolicTransformer I saw from the Internet shown as below, if I print the features it create, I can see features like mul(0.180, 0.908) and sub(X3, -0.058). Thus I believe it is possible to specify one input as a constant.

>import numpy as np
>from gplearn import genetic
>m1 = genetic.SymbolicTransformer(verbose=1, generations=3)
>m1.fit(np.random.rand(10,5), np.random.rand(10))
>print(m1)

>[mul(0.180, 0.908),
 mul(div(add(X4, X1), sub(X0, sub(X1, X0))), X2),
 div(add(X1, X4), add(sub(X4, div(X1, sub(X1, X0))), sub(add(mul(X3, X3), X2), X4))),
 div(sub(X2, div(X3, 0.278)), sub(X2, X0)),
 mul(div(sub(sub(X1, 0.481), mul(0.180, 0.908)), sub(X0, X1)), X2),
 div(X1, sub(X3, X1)),
 add(div(mul(mul(mul(X1, X1), add(X3, X1)), div(add(X1, X3), sub(X3, -0.058))), add(mul(add(X1, X0), sub(X4, -0.003)), sub(add(X4, X1), mul(-0.273, -0.567)))), add(div(add(add(X1, X4), mul(X1, X3)), add(mul(X1, X3), sub(X2, X0))), sub(add(add(X0, X1), div(0.575, X3)), add(add(X2, X3), sub(X2, X0))))),
 div(mul(div(-0.347, X1), div(X0, X3)), div(mul(0.180, 0.908), sub(X2, X0))),
 div(sub(X3, X0), sub(X1, sub(add(mul(X3, 0.713), div(X1, sub(X1, X0))), mul(mul(0.164, X2), div(X3, X0))))),
 add(div(div(0.575, X3), add(mul(add(X1, X0), sub(X4, -0.003)), sub(add(-0.120, X0), mul(-0.273, -0.567)))), add(div(add(add(X1, X4), mul(X1, X3)), add(mul(X1, X3), sub(X3, X1))), sub(add(add(X0, X1), div(0.575, X3)), add(add(X2, X3), sub(X2, X0)))))]

**Comment by trevorstephens** [comment]
This is duplicating #175 ... You want to specify the input type of a function, this is not presently supported. Indeed, constants and vectors of X can be inputs, but this done randomly.

**Comment by Gaiss** [comment]
Actually it is because I saw a research paper succeeded in doing this and I hope to redo its work. Now I know that the author of the paper probably has solved this question but I could not figure out his or her method. So if possible, could you please point out some directions that I can explore to solve the problem? Thanks a lot!

**Comment by trevorstephens** [comment]
The research paper succeeded doing it with `gplearn` or something else? Got a link to the paper @Gaiss ?

It would require moderately deep modifications to the code base to support this, those changes would likely reduce usability of the package and could create some big speed problems. I'm not ruling it out but would have to think real hard about a good implementation. You would need to make modifications to program initiation, the functions to support constraints, each of the evolutionary operations to check for the constraint at every step, it's not trivial.

**Comment by trevorstephens** [comment]
Off the top of my head I'd probably make a new abstraction for a constrained function type, and (to be benchmarked to see if necessary) have two methods for evolution, one with constraints and one without so that performance issues wouldn't hit non-constrained function users. I don't have any timeline for this work though. Just thinking out loud.

**Comment by jmrichardson** [comment]
> 
> 
> This is duplicating #175 ... You want to specify the input type of a function, this is not presently supported. Indeed, constants and vectors of X can be inputs, but this done randomly.

Hi @trevorstephens , how do you specify an input to a custom function is a constant?  I can't find reference in the documentation.   Thank you

**Comment by trevorstephens** [comment]
Yes that's right @jmrichardson , it is not presently possible to constrain the inputs to be of a certain type
