### ISSUE TITLE
How to understand tournament_size?

### ISSUE THREAD

**Issue by keven3696** [trevorstephens/gplearn#186]
From the docs:

"From the population, a smaller subset is selected at random to compete, the size of which is controlled by the tournament_size parameter. The fittest individual in this subset is then selected to move on to the next generation."

Based on my understanding from above, say: 

case 1:I have 1000 programs, and the tournament_size is 20. So I only need to randomly select 20 programs and evaluate these 20 programs to get the fittest one.
case 2: now the tournament_size is 100 instead of 20, now I have to evaluate 100 programs to find the fittest one.
I think case 1 is faster and computational cheaper, because I evaluate less programs' fitness.

However, the docs also mentioned:

"Having a large tournament size will generally find fitter programs more quickly and the evolution process will tend to converge to a solution in less time. A smaller tournament size will likely maintain more diversity in the population as more programs are given a chance to evolve and the population may find a better solution at the expense of taking longer. This is known as selection pressure, and your choice here may be governed by the computation time."

Why?

**Comment by keven3696** [comment]
I further read through the  evolution process. It seems small tournament size brings more diversity during corssover,right? Since more diversity might bring more randomness, so it takes more time to get ideal results. If this is the case, everything will make sense to me.

I tried to run SymbolicTransformer on a large dataset with customized functions and fitness metrics. The program runs very slow, even I set generations=1 and population=1000. Any idea how can I adjust other params to make it run faster without much adverse effects on fitness?

Thanks in advance.

**Comment by trevorstephens** [comment]
> It seems small tournament size brings more diversity during evolution process,right? Since more diversity might bring more randomness, so it takes more time to get ideal results. If this is the case, everything will make sense to me.

That's correct, that said very fast convergence might mean that the optimal solution is never found as the search space is much smaller with fit individuals dominating the evolution.

> I tried to run SymbolicTransformer on a large dataset with customized functions and fitness metrics. The program runs very slow, even I set generations=1 and population=1000. Any idea how can I adjust other params to make it run faster without much adverse effects on fitness?

`generations=1` would just result in a totally random set of programs, which would not be very useful. Are you running in parallel? `n_jobs` parameter controls how many parallel threads are running. Sometimes it can be faster to run many threads, sometimes it is faster to run only one thread, it depends how big your programs are and how many in the population as there's a fair bit of overhead in spinning up the parallel processes. You could also try to start with a small subsample of your data to get the evolution started, and then run another set of generations on the whole dataset using `warm_start` : https://gplearn.readthedocs.io/en/stable/advanced.html#continuing-evolution. Good luck 😄

**Comment by keven3696** [comment]
Thank you for your reply. That's very helpful.
