### ISSUE TITLE
Optimize speed: move np.errstate outside evaluation loop

### ISSUE THREAD

**Issue by danuker** [trevorstephens/gplearn#188]
**Is your feature request related to a problem? Please describe.**
I ran gplearn through a profiler, and I discovered that the `with np.errorstate` context statement takes a long time, longer than even the numpy function calls themselves.

**Describe the solution you'd like**

I would like to move and combine the `with` statements to a place that is executed less often.

Some options could be the `_parallel_evolve` or `fit` methods in `genetic.py`. Here, it would only happen once per generation, instead of once per individual. 
It would involve extending the long methods even more; but I can't think of any better place.

Do you think this is premature optimization?

**Additional context**

I ran with a population of 1000 over the cancer dataset, for 30 generations.
The total time for the whole program was 19.55s, and the profiler says 5.25s (or more than 26%) was spent entering and exiting the `with` statement.

![](https://i.imgur.com/ptm55Z0.png)

**Comment by trevorstephens** [comment]
Really interesting, thanks @danuker for the report! Could be a big boost in speed. Will look into it but at first blush this sounds very promising.

**Comment by danuker** [comment]
I was using numpy 1.16.1; I upgraded today to 1.17.2, and it seems gplearn runs quite slower, and that my optimization doesn't matter. Very strange. I will try to find out why 1.17 is slower.

**Comment by trevorstephens** [comment]
Are you able to open a WIP PR with your changes?

**Comment by danuker** [comment]
I'm a bit rusty, but I think I will be able to in 20 minutes.

**Comment by trevorstephens** [comment]
No rush, it's been like this for 5 years or so ;-)

**Comment by wulfihm** [comment]
With what did you do the speed/time analysis?

**Comment by danuker** [comment]
@wulfihm : I used the profiler that came with the Spyder IDE (not sure which one it is).

https://docs.spyder-ide.org/profiler.html

**Comment by danuker** [comment]
With numpy 1.18 and onwards, it is slower no matter what I do.

**Comment by trevorstephens** [comment]
Thanks for giving it a crack @danuker appreciate the efforts :+1:
