### ISSUE TITLE
Issue running example code

### ISSUE THREAD

**Issue by kcosta6289** [trevorstephens/gplearn#190]
I am trying to run the example code: gp_examples.ipynb.
I receive the following error after trying to run box 8: "AttributeError: module 'graphviz' has no attribute 'Source'"

I have doublechecked that graphviz is properly installed, and as far as I can tell, it is. I receive no error in Box 1 for "import graphviz". When I go to the folder for graphviz, I cannot find any file with the name 'Source'.
- Is the Source attribute an additional module that needs to be downloaded separate from graphviz?
- Is there another way to produce the graphic without using the Source attribute?

I am using Python 3.7 in Jupyter Notebooks.

**Comment by trevorstephens** [comment]
I just tried with the latest version of the python graphviz package. I would suspect that it is your installation of the graphviz dependency that is the problem. 

Make sure to follow: https://graphviz.readthedocs.io/en/stable/manual.html

And you will need graphviz installed in your system as well: https://www.graphviz.org/download/
