### ISSUE TITLE
Finding a custom cost function minima

### ISSUE THREAD

**Issue by ma7555** [trevorstephens/gplearn#193]
Is it possible to find a solution for a custom error function using gplearn?
the error function relies only on one argument, example:
```
def cost_fn(data, y=None, w=None):
    cost = 0
    if data[0] == 0:
        cost += 1000
    elif data[0] == 1:
        cost += 5000
    elif data[0] < 5:
        cost += 1000
    if data[1] == 3:
        cost += 2000
    if data[2] <= 5:
        cost += 500
    return cost

data = np.array([1, 3, 5])
print(cost_fn(data))
```
`7500
`

Note that I used (y_pred, y, w)  to avoid raising an error when calling:

`fitness_fn = make_fitness(cost_function, greater_is_better=False)`

I want to know if it is possible to find a solution for such problem using gplearn.
data is always 1D array

**Comment by profitablealgos** [comment]
I also wonder about this. I want to return a value that's not dependent on y and y_pred and w. But some other data. For example the F-Score of running the output transforms from the gp in to a XGBoost model and then use the F score as a fitness metric.

**Comment by trevorstephens** [comment]
The transformer makes the fitness evaluations based on each program independently so that is not currently possible @profitablealgos
