### ISSUE TITLE
Can't see the equations used as feature

### ISSUE THREAD

**Issue by CoteDave** [trevorstephens/gplearn#197]
Hi,

When gplearn is used as a feature engineering step with the SymbolicTransformer, is there a way to extract the symbolic equations of each component created ? 

For example:  
gp_features component1 = sin(X1)**2
gp_features component2 = X1+X2
gp_features component3 = X3*X10
etc.

This is an important feature if we want to keep the hole process as a "whitebox"

thanks !

**Comment by trevorstephens** [comment]
Hi there @CoteDave, After fitting you can just `print(est)` to see the programs.
