### ISSUE TITLE
Coefficient of each term in output model 

### ISSUE THREAD

**Issue by Lolojr** [trevorstephens/gplearn#198]
**Is your feature request related to a problem? Please describe.**
I noticed that when using the SymbolicRegressor in order to identify an underlying mathematical expression that best describes a relationship between a feature and a target, the algorithm only expresses an output model with coefficient of each term equal to one. For example, considering the 
following  model y = a*f(X1) + b*f(X2) that we are seeking, the Symbolic regressor will always give an output with coefficients equal to 1 : y_pred = 1*g(X1)+ 1*h(X2) + 1*js(X1,X2)....)

**Describe the solution you'd like**
I don't really have a solution but maybe a suggestion. Implement a function that consider the coefficent of each term in the output of the algorithm. @trevorstephens

**Comment by trevorstephens** [comment]
Not sure I follow, the solutions are in no way constrained to any given form, ie. it is not linear, so there isn't really any concept of coefficients. Not sure I really follow the decomposition you are expressing.

**Comment by Lolojr** [comment]
Hello, 
First of all thanks for taking time to answer my issue. Pardon me if I expressed myself poorly. 

Let's take the example of your documentation to illustrate my problem. In this latter you try to predict the model  ` y = X0**2 - X1**2 + X1 -1` by using SymbolicRegressor tool, who does it very well. If now we consider the following model ` y =  25*(X0**2) - 31*(X1**2) + 113*X1 -1` the gp symbolic tool won't be able to predict a simple model and will give a very complexe one since it does not  express the coefficient in front of each term of the model.  You can see by yourself your example modified to bring to light my issue in the following notebook : [https://github.com/Lolojr/GP_Symbolicregressor/blob/master/GP_SR.ipynb](url)

**Comment by Lolojr** [comment]
@trevorstephens can you enlighten me on my issue ?

**Comment by Lolojr** [comment]
@trevorstephens ?

**Comment by trevorstephens** [comment]
Sorry @Lolojr been a bit busy. The construction that the model takes is completely arbitrary and governed by the evolution. Putting constraints on every term is not supported sorry. Sounds like you are trying to do a box-cox transformation to your data automatically, that isn't what genetic programming seeks to do as support for interactions between features is almost guaranteed to come out of GP
