### ISSUE TITLE
INCREASE PRECISION in `est_gp._program`

### ISSUE THREAD

**Issue by avloss** [trevorstephens/gplearn#199]
sorry for all capitals, but it was a major issue for me, and I've almost turned away from your great tool because of this. GPLearn found the right solution for me, but when I looked at the formula the way your tutorial suggested, it produces something like:
`div(X0, sub(0.123, 0.123))`

formula was longer, but it included a lot of "???" like this. I had to look into `est_gp._program.__dict__` to find precise values, and formula (after some trivial simplification) proved to be quite useful! Now navigating though `__dict__` wasn't straight forward, but I was able to match values to their true values (something like `div(X0, sub(0.12290123, 0.12340123))`). And I understand your motivation behind showing something more "pretty", hence trimmed precision, and yeah it's an internal function, but you use it in your tutorial.

**Comment by trevorstephens** [comment]
All caps is considered rude by many online, including myself. I make this package as a free project using my own time to build, maintain and support it. Please show respect to the volunteers in the open source community who make the tools that you use.

That aside, you should be able to pretty easily make a custom string representation by modifying the inbuilt version for your needs.

https://github.com/trevorstephens/gplearn/blob/master/gplearn/_program.py#L238-L261

```
from gplearn.functions import _Function

def to_string(est):
    terminals = [0]
    output = ''
    for i, node in enumerate(est._program.program):
        if isinstance(node, _Function):
            terminals.append(node.arity)
            output += node.name + '('
        else:
            if isinstance(node, int):
                output += 'X%s' % node
            else:
                output += '%.8f' % node
            terminals[-1] -= 1
            while terminals[-1] == 0:
                terminals.pop()
                terminals[-1] -= 1
                output += ')'
            if i != len(est._program.program) - 1:
                output += ', '
    return output
```

Would probably do what you're asking
