### ISSUE TITLE
Please link to the git repo from docs homepage

### ISSUE THREAD

**Issue by bionicles** [trevorstephens/gplearn#200]
**Is your feature request related to a problem? Please describe.**
Just seems silly we have to google/exit the docs just to get to the repo

**Describe the solution you'd like**
A link to the git repo on the top of the home page of the docs

**Comment by trevorstephens** [comment]
There is a "edit on github" link at the top of every page, "open an issue" links on the front page as well as the contributing page, and source code can be viewed within the docs by clicking "source". Is that inadequate somehow?
