### ISSUE TITLE
Can we make custom functions that Standardize an Normalize?

### ISSUE THREAD

**Issue by JohnPaulR** [trevorstephens/gplearn#201]
I like that the program can explore common transformations, but I can not figure out how to normalize (mean & standard deviation of sample) or standardize (max & min of the sample) with it. Is it possible to implement custom function with inputs like the mean and standardization of the functions outputs on the sample?

**Comment by trevorstephens** [comment]
Hey there sorry for the delay, if I understand correctly, you can create custom functions that take one, or several, individual features of X, so you could perform a normalisation of a single input vector for example, but the custom functions do not presently have the ability to take the entire input data as a feature.

**Comment by trevorstephens** [comment]
See here for the API example: https://gplearn.readthedocs.io/en/stable/advanced.html#custom-functions

**Comment by LaGvidilo** [comment]
And look my fork modifications, a lot of functions added, I mean is a good
example. ;) bye

Le sam. 11 juil. 2020 à 02:15, Trevor Stephens <notifications@github.com> a
écrit :

**Comment by LaGvidilo** [comment]
Is LaGvidilo/GPlearn

Le sam. 11 juil. 2020 à 02:18, Cyril Coelho <cyrilcoelho67@gmail.com> a
écrit :
