### ISSUE TITLE
Why is a large proportion of candidates in the initial population = None?

### ISSUE THREAD

**Issue by nosb9124** [trevorstephens/gplearn#202]
Hello, 

I am working through the example notebook [https://github.com/trevorstephens/gplearn/blob/master/doc/gp_examples.ipynb](url) and am able to reproduce the same results.  

When I inspect the initial population `est_gp._programs[0]` only 139 candidates are a gplearn program and the remainder are `None`. I get similar results of a high proportion of the initial population being set to `None` when applying to my own regression problem. Why is this the case?

Line 222 of [https://github.com/trevorstephens/gplearn/blob/master/gplearn/_program.py](url) (I think this is the right place to look) implies this should never happen. 

Thank you!

**Comment by trevorstephens** [comment]
Programs that did not make it through selection to contribute to the next generation are removed from the old generations due to the high memory use it causes, you can find the logic here: https://github.com/trevorstephens/gplearn/blob/master/gplearn/genetic.py#L502-L514

**Comment by nosb9124** [comment]
Thanks!

**Comment by trevorstephens** [comment]
You're welcome :-)
