### ISSUE TITLE
There are some problems in multicore computing

### ISSUE THREAD

**Issue by hashfury42** [trevorstephens/gplearn#204]
Hi，when I set the 'n_jobs' parameter for SymbolicRegressor, it seems that only the 1st generation can use all my cpu cores, and only one CPU can be used since the second iteration. My system is WIN 10,  16 core E5-2670 CPU. 

Did anyone else have the same problem？

**Comment by wulfihm** [comment]
Well, why do you think that? Do you have example code?

**Comment by Lucasgong** [comment]
I meet the same problem on linux! Have you solved it? 
I really need help

**Comment by rll2021** [comment]
I see the same problem as well.
Furthermore, one does not get the same population using different values of n_jobs.
A fix would be useful; I would like to use million point data-sets, but this takes too long on one core!

**Comment by trevorstephens** [comment]
You should get the same results with different job sizes. The random seeds are propogated through the evolution. I see you "hacked" the codebase in another issue so it is possible that you broke that careful handling of the random state along the population and through the generations. Tests on n_jobs equivalency is passing https://github.com/trevorstephens/gplearn/blob/master/gplearn/tests/test_genetic.py#L850-L897

**Comment by cyy5358** [comment]
Same problem as well.
The CPU usage while running gplearn is quite low and it seems that only one CPU core takes part in calculating. It may be joblib to blame?
@trevorstephens
