### ISSUE TITLE
Specify terminal set

### ISSUE THREAD

**Issue by yahoo0742** [trevorstephens/gplearn#206]
Hi,

I have several question of using gplearn. Tried to ask on stackoverflow but unfortunately haven't got answer yet. And I checked "gplearn" tags on stackoverflow, few questions got answered. I didn't find a forum of somewhat for posting questions and then turn here, though it shouldn't be a proper place to ask questions here. Where can we ask a question?

My actually questions are 1. Can gplearn support specifying terminal set? 2. Can gplearn support strong typed functions like costuming a function which only accept a boolean argument.

Thanks

**Comment by trevorstephens** [comment]
Hi @yahoo0742 sorry I don't really use stackoverflow, but I don't mind users asking questions here.

These answers are quite short, no and no. Terminals are automatically chosen from the features and random constants, there is some interest in constrained functions in #175 but I haven't implemented this yet.

**Comment by yahoo0742** [comment]
> Hi @yahoo0742 sorry I don't really use stackoverflow, but I don't mind users asking questions here.
> 
> These answers are quite short, no and no. Terminals are automatically chosen from the features and random constants, there is some interest in constrained functions in #175 but I haven't implemented this yet.

Thanks for your answer and the lovely library!

**Comment by trevorstephens** [comment]
@yahoo0742 no worries at all! 😄 

Can you give an example of what terminal set you'd like to see possible to chose from, and why? May be an easy enhancement potentially if there is much interest around it.

**Comment by yahoo0742** [comment]
> @yahoo0742 no worries at all! 😄
> 
> Can you give an example of what terminal set you'd like to see possible to chose from, and why? May be an easy enhancement potentially if there is much interest around it.

@trevorstephens, In my case, it is preferred that the terminal set only have the input variables, 1, and 0 (2 constants). Since gplearn generates some random numbers, then I need to have more functions (like bitwise and, or, not) to get 1 and 0. Simply speaking, my work can be much easier if I can specify terminals. But for now, because my problem is not complicated, the requirement can be satisified by adding functions ( I was struggling in reading Deap documents, hard to use to me).  Thanks.
