### ISSUE TITLE
"Weights" for functions in function_set

### ISSUE THREAD

**Issue by smheidrich** [trevorstephens/gplearn#209]
**Is your feature request related to a problem? Please describe.**
It's not currently possible to specify a "preference" for certain functions to appear in expressions.

**Describe the solution you'd like**
It would be great if one could specify "weights" for the operators allowed in symbolic expressions, which are then taken into account when computing the penalty for the expression length. So e.g. one could specify that `add` has a weight of 2 and `log` has a weight of 1, making it less likely for the former to appear in expressions.
Alternatively, similar to the approach taken in gplearn for custom fitness functions, perhaps users should be able to specify their own function that computes the penalty for a given symbolic expression. This would of course be more general, but perhaps slightly less user-friendly for those who don't want to write code that walks through an expression tree just to compute a weighted length.

**Additional context**
Some other symbolic regression libraries have this: e.g. [ellen](https://github.com/lacava/ellen) has an `op_weight` setting for this exact purpose. I could've sworn I also saw this somewhere else, but can't remember where.

**Comment by trevorstephens** [comment]
Interesting idea. I think perhaps slightly related to #126 and might be nice to expand this API to allow more customisation for those so inclined. Will have to think through how that would also cater to more "power users"
