### ISSUE TITLE
Least Correlation

### ISSUE THREAD

**Issue by jmrichardson** [trevorstephens/gplearn#211]
Hi @trevorstephens 

Thank you so much for this really nice package! I have been modifying it a bit for my use case and really have learned a lot by looking at your code.  I have a question regarding this from the documentation:

`From the hall of fame, it will then whittle down the best programs to the least correlated amongst them as controlled by the n_components parameter. `

Is there a way to retrieve the correlation between the n_components?  I see the raw fitness (spearman correlation) for each program is recorded but can't find any reference to the correlation amongst the n_components. 

Thanks

**Comment by trevorstephens** [comment]
https://github.com/trevorstephens/gplearn/blob/master/gplearn/genetic.py#L564 is where the correlations begin to be evaluated. You'd need to store these to the object somehow to inspect them, but if you're happy to modify the code then that's where you can find them
