### ISSUE TITLE
grouping several single trees to form a single individual

### ISSUE THREAD

**Issue by pinouche** [trevorstephens/gplearn#213]
I am trying to using several trees and to combine their outputs by writing a custom metric function.

However, I noticed that the metric functions attributes a score tree by tree (individually) and does not access all the population at once.

Is there a way to do so?

Alternatively, is there a way to set the fitness of each tree manually and then re-introducing them in the population to evolve?

Thanks

**Comment by trevorstephens** [comment]
Sorry not supported
