### ISSUE TITLE
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by jmrichardson** [trevorstephens/gplearn#214]
Hi, I am receiving this error and hoping someone can help:

```
/home/jmrichardson/tactory/tactory/gplearn/genetic.py:554: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  i in hall_of_fame]])
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    hall_of_fame=1000, components=50, n_jobs=50)
  File "/home/jmrichardson/tactory/tactory/genetic.py", line 48, in genetic
    gp.fit(X, y)
  File "/home/jmrichardson/tactory/tactory/gplearn/genetic.py", line 556, in fit
    evaluation = np.apply_along_axis(rankdata, 1, evaluation)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 361, in apply_along_axis
    axis = normalize_axis_index(axis, nd)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

```
I have made a few modifications of the gplearn source code to work with my use case but not sure what could cause this error.  Thanks in advance for any assistance

**System information**
>>> import platform; print(platform.platform())
Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
>>> import sys; print("Python", sys.version)
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.19.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.4.1
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.23.2
>>> import joblib; print("Joblib", joblib.__version__)
Joblib 0.16.0
>>> import gplearn; print("gplearn", gplearn.__version__)
gplearn 0.4.1

**Comment by jmrichardson** [comment]
Sorry, this is not a bug with gplearn, rather a bug with some custom functions and their output format (series).

**Comment by trevorstephens** [comment]
Sorry I was not able to get back to you sooner @jmrichardson ... Would you be able to share the custom function? Perhaps additional sanity checks could be added to the function factory to stop such issues for others in the future?

**Comment by jmrichardson** [comment]
Hi @trevorstephens ,

So, I don't think my use case is what this package was meant to do based on what I have read in other issues here.  I am essentially using gplearn to do composite technical analysis indicators (genetically combining indicators).  However, I have had to make some source code modifications to support custom functions which take in a close price and tunable parameters.  For example, here are a couple of custom functions:

```
def ind(close, timeperiod):
    return talib.RSI(pd.Series(close).astype(float), timeperiod=timeperiod)
rsi = make_function(function=ind, name='rsi', arity=2, parms=['timeperiod'])

def ind(close, timeperiod):
    return talib.BBANDS(pd.Series(close).astype(float), timeperiod=timeperiod)[0]
bbands_upper = make_function(function=ind, name='bbands_upper', arity=2, parms=['timeperiod'], index=0)
```

As you can see, I have added additional parameters to the function object such as parms and index which are used in the Symbolic Transformer.

To fix the problem for me, as some of the functions return series instead of arrays, i just updated this block of code to force the output to be array in genetic.py:

```
            evaluation = np.array([np.array(gp.execute(X)) for gp in
                                   [self._programs[-1][i] for
                                    i in hall_of_fame]])
```

I suppose you could verify that custom functions generate arrays vs series? 

Thank you for this very well written package!  I have been thinking about how to go about doing something like this for a while and finally came across gplearn and decided to give it a try.  I think I got all the issues worked out but don't want to jinx myself :)

**Comment by trevorstephens** [comment]
Thanks for that @jmrichardson , I'll have a look into the sanity checks for custom functions to see if we can help out users better. It probably doesn't change what I'd add to the checks, but can you point me to `talib`? 

Thanks for raising the issue, hope you are able to achieve whatever you are trying to get done :-)
