### ISSUE TITLE
Constraint in gplearn

### ISSUE THREAD

**Issue by JinkaiGUAN** [trevorstephens/gplearn#216]
**Is your feature request related to a problem? Please describe.**

When I am solving fluid dynamics problems using gplearn, I found it is really difficult for me to put some constraints on the individual, such as integration equal yo one. So do you have any simple or underlying idea for such problem?

**Describe the solution you'd like**

**Additional context**

**Comment by trevorstephens** [comment]
You cannont constrain the program but you could apply a heavy penalty in a custom fitness function which might have a similar affect. https://gplearn.readthedocs.io/en/stable/advanced.html#custom-fitness
