### ISSUE TITLE
Is there a way to directly use the trained model?

### ISSUE THREAD

**Issue by superminghui** [trevorstephens/gplearn#217]
Hi, sorry to bother you.
I have an idea but I did not find the corresponding method in the documentation
I spent some time studying the parameters, but the input and output of my model are quite special.
est_gp = SymbolicRegressor(population_size=5000,
                           generations=20, stopping_criteria=0.01,
                           p_crossover=0.7, p_subtree_mutation=0.1,
                           p_hoist_mutation=0.05, p_point_mutation=0.1,
                           max_samples=0.9, verbose=1,
                           parsimony_coefficient=0.01, random_state=0)

I have two inputs and only one output node, but this output is an array with more than 20,000 elements. This matrix represents the distribution of energy.

I used Autokeras and Keras to train it in advance. Autokeras showed that if I want to get good results, the number of parameters in my neural network will reach more than two hundred thousand.
I want to try gplearn to find a mathematical formula to represent a relationship.

So what I want to ask is, is there any way to make gp directly process the existing model.
That is to say whether I can load the existing model into gplearn, and then extract the potential formula

**Comment by trevorstephens** [comment]
The existing model meaning a neural network? No, gplearn uses it's own representation and only takes as input a regular X and y training datasets like most sklearn estimators.

**Comment by superminghui** [comment]
> The existing model meaning a neural network? No, gplearn uses it's own representation and only takes as input a regular X and y training datasets like most sklearn estimators.

Yes, it means a exsited neural network.
Okay, Thank you so much.
But one more question.

As I described before, I have used autokeras and keras to get a neural network by training my data. And from it, I probably know that this neural network has about 200,000 parameters.
So when I input my data to gpleran for training, how do I probably need to set these two parameters population_size=? generations=? for such a large dataset

Can you give a suggestion?
Thans sosososo much!

**Comment by trevorstephens** [comment]
Sorry but those parameters need to be tuned for every problem. I doubt you will have a fun time training a genetic model with that many parameters, it will take forever as we don't have the benefit of GPUs in gplearn

**Comment by superminghui** [comment]
> Sorry but those parameters need to be tuned for every problem. I doubt you will have a fun time training a genetic model with that many parameters, it will take forever as we don't have the benefit of GPUs in gplearn

Thanks so much
