### ISSUE TITLE
Is there any method for multi output of symbolic regression?

### ISSUE THREAD

**Issue by SamWqc** [trevorstephens/gplearn#218]

**Comment by trevorstephens** [comment]
Not built in to gplearn presently. But you could try to do a one-vs-rest approach using sklearn's tools https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsRestClassifier.html

**Comment by LuoYuanzhen** [comment]
As far as I know, "multi-tree" can be used to multi-output symbolic regression tasks. Also, an individual of Cartesian Genetic Programming (CGP) is able to produce multi-formula thanks to its graph representation. 
So, you can try google "multi-tree" or "cartesian genetic programming" for more details.
