### ISSUE TITLE
Survival of the fittest

### ISSUE THREAD

**Issue by rll2021** [trevorstephens/gplearn#219]
Darwinian evolution assumes the fittest survive. However, gplearn mutates whatever program(s) is(are) selected for the tournament, removing the parent from the population, even if the parent is fitter than the offspring. 

I think it would be advantageous to first reproduce each program selected for the tournament, and mutating only the original (or only the copy). One would be left with a growing population, guaranteed to contain the fittest programs found so far. For population control, one might sort by fitness once per generation and drop the least fit

I have hacked up a local copy of the code to reproduce the parent. (It's definitely a hack: Since I have not figured how to grow the population, a random program gets dropped for every one I copy.) With a small population and a large number of generations, one does see loss of diversity. But before reaching homogeneity, I usually find a reasonable program. Without the hack, the "best" are most often unreasonable.

**Comment by trevorstephens** [comment]
You can increase the amount of reproduction by reducing the probabilities of the other mutation methods to sum less than one if you want to. https://gplearn.readthedocs.io/en/stable/intro.html#evolution

**Comment by rll2021** [comment]
I am fully aware that I can probabilistically induce reproduction. My 
point stands: as soon as a program is selected for mutation (or 
crossover), it is doomed by the current code.

trevorstephens wrote:

You can increase the amount of reproduction by reducing the 
probabilities of the other mutation methods to sum less than one if you 
want to. https://gplearn.readthedocs.io/en/stable/intro.html#evolution 
<https://gplearn.readthedocs.io/en/stable/intro.html#evolution>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/trevorstephens/gplearn/issues/219#issuecomment-771145456>, 
or unsubscribe

**Comment by trevorstephens** [comment]
Your idea is that the fittest individual should live forever. That is not the case in darwin's theories, nor in gplearn.
