### ISSUE TITLE
Max depth

### ISSUE THREAD

**Issue by nasergh** [trevorstephens/gplearn#222]
Hello,
i see trees growth very fast  
for example i set init depth = (2,5) but i see program generate tree with 16 features!
i need a setting that restrict the max depth of tree, for example i want to just check different combination of 5 variables not more.
thanks 
best regards

**Comment by trevorstephens** [comment]
Hey there, yes they can grow quite fast. This can be reigned in by increasing your parsimony coefficient but there is no hard stop functionality to stop programs getting bigger. It seems you may misunderstand depth as well, depth is the number of "layers" that the syntax tree has, not the number of nodes. See here for the tree representations (the coloured tree-like representations of the programs) https://gplearn.readthedocs.io/en/stable/intro.html
