### ISSUE TITLE
What does p_point_replace do?

### ISSUE THREAD

**Issue by rodschermitg** [trevorstephens/gplearn#223]
Hello Trevor!

Not sure if this is the right place to ask this question, but I’m new to GP and am struggling to understand what the p_point_replace parameter does.

Having read the docs, I currently understand that a tournament winner is firstly chosen with probability p_point_mutation to perform point mutation on. Am I correct in the assumption that p_point_replace is then imposed on all nodes of said tree, denoting the probability that the actual mutation process will be performed on each of the nodes?

If that is the case, then why isn’t it possible to specify an equivalent probability for the other mutations? Any help or short explanation would be greatly appreciated!

Also, I’m using gplearn for my thesis about symbolic regression. Do you have a preferred way to be cited? I’m currently just linking to the readthedocs web page.

Kind regards

**Comment by trevorstephens** [comment]
Hi @rodschermitg ... Yep, `p_point_mutation` is the liklihood that that type of evolutionary process happens on the tourny winner. `p_point_replace` essentially is how severe that mutation will be. ie lots of nodes replaced with other random nodes or fewer. Other types of evolutionary processes don't really have any way to make them more or less altering, they are more random in nature. I hope that helps?

You can cite the docs, or the github repo, if you like. But I'd love to see the results of the work whenever you're ready. I have some vague idea of collecting uses of the package into a page on the docs. Perhaps a linked set of pdfs with maybe a very brief description or something like that would be cool. Be happy to hear your ideas on that though

**Comment by rodschermitg** [comment]
Thanks for the reply!

So p_point_replace essentially regulates how many nodes in a tree will undergo point mutation. Meanwhile, other types of mutation such as hoist mutation will be performed on one node (and its corresponding subtree) at max. Is that correct?

I'd be willing to send you a pdf when I'm done. It's written in German however, so I'm not sure how beneficial that would be for you.

**Comment by trevorstephens** [comment]
> So p_point_replace essentially regulates how many nodes in a tree will undergo point mutation. Meanwhile, other types of mutation such as hoist mutation will be performed on one node (and its corresponding subtree) at max. Is that correct?

Yep that's correct
