### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Trepetsky** [trevorstephens/gplearn#228]
The problem appeared after updating the dependent components.
Gplearn is installed. The problem is observed on 2 computers. 

Traceback (most recent call last):
  File "C:\Users\User\Desktop\gplearn.py", line 1, in <module>
    from gplearn.genetic import SymbolicRegressor
  File "C:\Users\User\Desktop\gplearn.py", line 1, in <module>
    from gplearn.genetic import SymbolicRegressor
ModuleNotFoundError: No module named 'gplearn.genetic'; 'gplearn' is not a package

**Comment by trevorstephens** [comment]
What components are you referring to?

**Comment by Trepetsky** [comment]
> Какие компоненты вы имеете в виду?

Numpy, scipy, etc.

**Comment by trevorstephens** [comment]
Please provide versions of these as well as python, scikit-learn

**Comment by Trepetsky** [comment]
> Пожалуйста, предоставьте их версии, а также python, scikit-learn

On 1 PC:
Numpy 1.20.2
Scipy 1.6.3
Scikit-learn 0.24.2
Python 3.9.5

On 2 PC:
Numpy 1.20.2
Scipy 1.4.1
Scikit-learn 0.23.1
Python 3.8.3

**Comment by trevorstephens** [comment]
Thanks, what command are you running to import to trigger the import error?

I'll try to investigate soon but seems like an unusual error unrelated to these packages as this is pretty much top level python stuff, perhaps something to do with your virtualenv. Can you run `pip freeze` for me?

**Comment by trevorstephens** [comment]
Also possible issue is you may have a project filename with the same name as the package, in which case it will try to import that file first instead of the package. Rename your project filename and then you can import the package instead of the file if that is the case.

**Comment by Trepetsky** [comment]
> Also possible issue is you may have a project filename with the same name as the package, in which case it will try to import that file first instead of the package. Rename your project filename and then you can import the package instead of the file if that is the case.

Yes. Thanks for the help. It was about the name of the file. I apologize for wasting my time with such probably stupid mistakes. I've been learning Python for so long. Anyway, I'm a chemist, not a programmer.

**Comment by trevorstephens** [comment]
All good @Trepetsky glad you were able to solve the issue :smiley: 

I remember first running into that issue several years ago, and it was code supplied by one of my professors at school! So don't worry, happens to us all, chemist or python teacher or otherwise :smiley:
