### ISSUE TITLE
SymbolicTransformer stuck with parallel or n_jobs= -1 option

### ISSUE THREAD

**Issue by snassimr** [trevorstephens/gplearn#23]
Hi ,

I don't succeed to run some even simple example with n_jobs parameter other than 1.

The script is stuck and failed to finish. I am using Windows machine .

For example [this one : ](http://gplearn.readthedocs.io/en/stable/examples.html#example-2-symbolic-tranformer).

Any solution ?

**Comment by trevorstephens** [comment]
I'd need more information I'm afraid. Any tracebacks or anything? Closing for now.
