### ISSUE TITLE
SymbolicClassifier Multi-Class

### ISSUE THREAD

**Issue by OUStudent** [trevorstephens/gplearn#233]
So I was trying to get the Symbolic Classifier working for a multi -class problem but I keep getting the following error:

ValueError: y contains 3 class after sample_weight trimmed classes with zero weights, while 2 classes are required.

I have three classes, [0, 1, 2] as part of my Y target variable. The 'check_classification_targets' function worked correctly by labeling the problem as multi class but apparently you guys only allow binary classification as n_trim_classes can only be equal to 2, but will be greater if there are more than one class....

How did you guys do multi class classification with symbolic classifier??

**Comment by trevorstephens** [comment]
Only binary classification is supported presently, but you could try one of the sklearn wrappers to expand to multiple labels. https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsRestClassifier.html#sklearn.multiclass.OneVsRestClassifier

**Comment by trevorstephens** [comment]
Duplicates #207
