### ISSUE TITLE
SymbolicTransformer Fitness Functions

### ISSUE THREAD

**Issue by powsns** [trevorstephens/gplearn#234]
I’m using SymbolicTransformer but it automatically exits the program after going through only one generation whenever I use fitness functions other than the pre-defined Pearson function, even if I set the generations parameter to be more than one. Do you know why this is happening?

**Comment by trevorstephens** [comment]
Well, you've given no info about the dataset, the custom metric, what the metric is reporting in the first generation, or anything specific about what "exit" means. So no. I do not know why it is happening. Total spit ball in the dark is the custom metric returns a value beyond the threshold eary and it's done what it should do and stopped creating more generations. If you really want help, please try to provide a small self contained example and some actual detal.

**Comment by pennymax** [comment]
@twang4815 take a try to change the parameter 'stopping_criteria' to a larger number than the default 1.0? I encountered similar issue before and fixed it by this way.
