### ISSUE TITLE
gplearn package is not found / cannot be installed with Anaconda 2021.5

### ISSUE THREAD

**Issue by Papagaiou** [trevorstephens/gplearn#237]
**Is your feature request related to a problem? Please describe.**
I was able to install gplearn with winpython. However I would prefer to continue using Anaconda. Unfortunately it seems that there is no working package in core and conda-forge.

**Describe the solution you'd like**
Could you develop a supported "conda" install?

**Additional context**

**Comment by trevorstephens** [comment]
What benefits would come from implementing that? I haven't used anaconda in many years so cannot speak to it lately. Can't you just pip install into the env?

**Comment by trevorstephens** [comment]
Just become aware of a conda-forge version available here: https://anaconda.org/conda-forge/gplearn
