### ISSUE TITLE
Imaginary numbers in gplearn output

### ISSUE THREAD

**Issue by HuangHam** [trevorstephens/gplearn#244]
When I include functions like exp and sqrt in SymbolicRegression, it's easy to end up with imaginary numbers such as sqrt(-1.4) or log(-4) lurking in the fitted formula. Even when my feature values are all positive. Is there a way to avoid this?

**Comment by trevorstephens** [comment]
They will not be evaluated as imaginary numbers as these are not just regular square roots or logs, they are "protected" versions of the functions, see here: https://gplearn.readthedocs.io/en/stable/intro.html#closure

**Comment by HuangHam** [comment]
Is it on your agenda to incorporate sympy into your API? so the output program can be more readable? I'm sure we would appreciate that a lot!

**Comment by trevorstephens** [comment]
Not at this stage, I might consider something like a helper function to export native `gplearn` programs to Sympy but embedding sympy into the engine won't happen.

**Comment by remiadon** [comment]
Hi there, 

Lately I have been working on "re-implementing" gplearn with sympy expressions at the core.
I've named the project [symkit](https://github.com/remiadon/symkit/tree/master/symkit)

IMO working with sympy has some great pros, but also some cons, which I'd be open to explain.
Plus my project is pretty new and I don't pretend it to be as robust as gplearn.
Also, I'd like to mention gplearn's doc is of great help when one is new to genetic programming.

Just for curiosity, @trevorstephens why `sympy into the engine won't happen` ?
