### ISSUE TITLE
Falling into local optimum

### ISSUE THREAD

**Issue by HuangHam** [trevorstephens/gplearn#246]
Great package! So I'm trying to recover a function which is a linear function inside of a logistic function. If I self define the logistic function in the function set, gplearn finds it really quickly. However, if I only use the exponential along with other basic arithmetic, no matter what hyper parameter I tune, it always falls into a long formula that starts with the node exp( ... ). In theory the function set should be enough for gplearn to recover the functional form of the logistic function, but somehow it doesn't. My hypothesis is that maybe the exp function serves as the best starting node and the subsequent generations were not able to rule it out, hence stuck in a local optimum unable to get out because the truel logistic function starts with a inv() function. Tuning the parsimony parameter or hoist mutation don't seem to help. Is there anything I'm missing here or it's just an intrinsic limitation of the gp algorithm?

**Comment by Riuza-c-137** [comment]
I would try to tune the tournament_size parameter lower and lower. 
See : https://gplearn.readthedocs.io/en/stable/intro.html#selection

If my understanding is correct : first, you have a population of a certain size, then potential expressions are choosen randomly in this population (based on the tournament_size), and only their fitness are evaluated, finally the best are selected.

This acts like a tunable diversity parameter where it does not always select the actual best fit of expressions, letting a chance global optimum to appear, but it will be longer.

**Comment by trevorstephens** [comment]
You could also try upping the point mutation to try and create more variety. If you know the functional form you want then creating a custom function with the framework you need could help as well https://gplearn.readthedocs.io/en/stable/advanced.html#custom-functions

In general I won't provide much guidance for specific use-cases as a github issue, this is meant for reporting bugs and requesting features.
