### ISSUE TITLE
1. can gplearn do Parallel computing 2. lagre coefficient?

### ISSUE THREAD

**Issue by sky8fall** [trevorstephens/gplearn#247]
hi~
1. Can Gplearn speed up on multi-node servers (parallel)? I used PC CPU to reproduce some simple equations. But a slightly more complex form of the equation leads to an unacceptable result (too messy)
2. I noticed that the parameter variation is set within a very small range（-0.01~0.01？）, and complex coefficients are usually done by division. For example, 6x is represented as x/0.166, so a coefficient, e.g. 130000, seems to be a big challenge for GP，so how to deal with big coefficients.
thanks a lot

**Comment by trevorstephens** [comment]
Yes, it's controlled via the `n_jobs` parameter as described in detail in the documentation... https://gplearn.readthedocs.io/en/stable/advanced.html#running-evolution-in-parallel

I cannot comment on individual problems so you'll need to experiment with the parameters yourself.
