### ISSUE TITLE
Evaluate fit to a manually input formula

### ISSUE THREAD

**Issue by HuangHam** [trevorstephens/gplearn#248]
Is it possible to say I manually input a formula such as x+y = z for gplearn to tell me how well it fits my data? So that I can run symbolic regression to try to discover a formula better than the existing one. This function would be helpful to my research where I'm trying to explore if there is a better fit interpretable formula than an existing one. Another feature I would find useful is to require symbolic regression to use all possible predictors. For example, if I have both x and y as predictors, I want to rule out any formula that only involves x or y. Thank you! Really appreciate this package.

**Comment by trevorstephens** [comment]
I described a hacky workaround here, but it is not supported as a first class feature currently https://github.com/trevorstephens/gplearn/issues/36#issuecomment-557938076

The second one is not possible without hacking the source code
