### ISSUE TITLE
How to force minimum length to be 2?

### ISSUE THREAD

**Issue by replacementAI** [trevorstephens/gplearn#249]
Whenever I run SymbolicRegressor, the average length decreases to between 1-2 and best length decreases to 1 in a few generations (it also has a weird output of a number like -.428, but I'm not sure how to use that). This happens regardless of the population size, generations, parsimony coefficient, and function set, so I want to know if there is a way to force the minimum length to always be 2?

**Comment by trevorstephens** [comment]
No sorry that is not supported

**Comment by replacementAI** [comment]
I think I "fixed" it, I made all genetic operations = 0 except for p_point_mutation = 1

**Comment by trevorstephens** [comment]
Ah that's pretty clever actually 🤩
