### ISSUE TITLE
What is a good way to avoid generating redundant individuals during the evolution process?

### ISSUE THREAD

**Issue by zhenlingcn** [trevorstephens/gplearn#250]
**Is your feature request related to a problem?**
This is really a good package for the symbolic regression task. Yet, I find that this package will output several identical individuals at last. 

**Describe the solution you'd like**
I know this is a rather common phenomenon if we use a large tournament size. However, is it possible for me to implement a rejection-sampling strategy to avoid generating repetitive individuals? The code is so complex, I need some instructions. Thanks!

**Comment by trevorstephens** [comment]
I assume you are using the symbolic transformer, I can't really help on individual applications but you can try having a larger `hall of fame` ... The package already seeks the least correlated individuals out of those. Beyond that you will need to play with the evolution parameters to try and achieve a more diverse group of programs.

**Comment by zhenlingcn** [comment]
@trevorstephens Thanks for your response. Your advice is valuable, and enlarging the hall-of-fame size is a good idea. I hope other enhancement features will be supported in the future.
