### ISSUE TITLE
Consider releasing 0.4.2 to PyPi due to test incompatibility with current sklearn

### ISSUE THREAD

**Issue by EvilMav** [trevorstephens/gplearn#256]
**Describe the bug**
Current PyPi release refers to `sklearn.utils.testing` in the tests, which was moved. **The current `master` seems to have already adressed the issue**, but it is not on PyPi. This leads to a packaging issue for OS maintainers because tests can not be run on build with current `sklearn`.

**Expected behavior**
PyPi should have a minor release with up-to-date dependencies.

**Actual behavior**
` ModuleNotFoundError: No module named 'sklearn.utils.testing'`

@trevorstephens: sorry to ping you directly, but you're the only PyPi maintainer =)

**Comment by trevorstephens** [comment]
Yes, it's a good idea @EvilMav , been a bit lazy on some tests failing as well. Will try to put some time into it soon.

**Comment by trevorstephens** [comment]
New version released @EvilMav 

https://pypi.org/project/gplearn/0.4.2/

tests should be passing now on current sklearn and their next release in a week or two
