### ISSUE TITLE
Is it possible to access for each gen the transformation applied the original features?

### ISSUE THREAD

**Issue by ghost** [trevorstephens/gplearn#26]
The code is awesome but It would be good in my opinion to be able to know for instance that at : 

- generation 1 the subset of features is **add(var_1,var_2)...**
- generation 2 the subset of features is **std_add(var_1,var_2)...**
etc ...

**Comment by trevorstephens** [comment]
Hi @toto12345678 ... Your example isn't totally clear to me, you want to see all the subtrees in the entire population? At what depth? Can you explain further what you are looking for and how it would be generally useful to other users?
