### ISSUE TITLE
readable/diagram program expression

### ISSUE THREAD

**Issue by rtaromax** [trevorstephens/gplearn#27]
Hi, how can I output the best program as a readable expression or a diagram?

**Comment by trevorstephens** [comment]
Hi @rtaromax does the example at [here](http://gplearn.readthedocs.io/en/stable/examples.html) work for you?

ie. Using `print est._program` to print the final solution, or using the `export_graphviz` method to visualise it as a program tree?

**Comment by trevorstephens** [comment]
I could probably add this usage to the "advanced features" section of the docs I guess...
