### ISSUE TITLE
what hyperparameter/s control/s the variables in final expression?

### ISSUE THREAD

**Issue by MohammadSoltani100** [trevorstephens/gplearn#272]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

first of all, big thanks for the great work

question is: 
suppose that I have 5 input variables (5 independent X), in the final expression but, I see less than 5.
1- what hyperparameter/s control/s this situation?

2- generally what are the most important hyperparameters (for tuning) in gplern?

Thanks for consideration

**Comment by trevorstephens** [comment]
Detailed discussion of the hyperparameters in the docs: https://gplearn.readthedocs.io/en/stable/intro.html

**Comment by MohammadSoltani100** [comment]
Thank you!
