### ISSUE TITLE
normalization for input? 

### ISSUE THREAD

**Issue by AmosJoseph** [trevorstephens/gplearn#276]
Is it necessary to do normalization for input using Genetic Programming implemented by gplearn? 
Will the predictive accuracy be improved by doing this?

Is Genetic Programming a tree model? 
It seems there is no need  to do normalization tree model.

**Comment by trevorstephens** [comment]
If your purpose is to get an equation out of the process then normalisation would not be appropriate. If you just want predictive accuracy then try it and see if it helps. GP is not a decision tree in the sense of partitioning data, it is a symbolic equation model. Please see the docs for more.
