### ISSUE TITLE
Is it possible to access programs inside make_fitness? 

### ISSUE THREAD

**Issue by fnssm26** [trevorstephens/gplearn#277]
Hello!

I would like to know if it is possible to access the expressions inside make_fitness. 
Currently I can only access the three parameters y, y_pred, and w. 

The idea is to run a set of simulations using an expression to make decisions (to solve prescriptive problems where an objective function needs to be minimized).

Best regards,
fnssm

**Comment by trevorstephens** [comment]
It isn't possible to access the program, just assess goodness of fit via the `y`'s. You may be able to modify the source code to support that in `_program.py` though it is not on my roadmap to support it out of the box presently.
