### ISSUE TITLE
[Question] How to use gplearn in comparison to neural networks?

### ISSUE THREAD

**Issue by meteoDaniel** [trevorstephens/gplearn#280]
Dear gplearn Community, 

unfortunately there is no discourse forum, so I am using this way to reach out to you. I am just having some questions before I will dive deeper into gplearn. 

1. Using LSTM or other architectures,  all describing features are feed into the neural network at once. Should I do the same with gplearn?
My problem I want to solve: Prediction of heat demand, and we have to deal with different pattern depending on temperature, calendar , sunshine duration and some more. 
Another option could be to just train the model on e.g. the 30 most similar days. I am asking because I think this would make the final function much easier. Covering all the different patterns in one equation sounds very hard to reach. Sometimes it is more like x**2 and sometimes more like sinus. Is the algorithm able to catch these different patterns with one single fit? 

2. A-Priori Information: 
You have explained that it make sense to provide additional functions to make the model more stable ( I really like stuff like this btw. ) 
So If I know that the correlation between temperature and the target can be described by sigmoid function , I should 

3. Data - shift 
Unfortunately we are dealing with a huge datashift in time since heat demand is rapidly decreasing due to energy crisis in europe. Do you have any ideas how to deal with it? 

Thanks a lot for your support!
I can offer to create another example for the docs when I am finished the first runs.

**Comment by trevorstephens** [comment]
1. All features are included in your `X`. I can't comment on whether the algorithm will find your best fit if it is constantly changing, but including the appropriate functions like `sin` might help. 
2. Sure you can include a sigmoid if it makes sense.
3. I can't comment on individual problems
