### ISSUE TITLE
question about _weighted_pearson

### ISSUE THREAD

**Issue by LotuSrc** [trevorstephens/gplearn#288]
I have read the source code of _weighted_pearson funtion in fitness.py. Why dose this function return np.abs(corr)? The corr should be in range -1 ~ 1, but in the function it's in 0 ~ 1.

**Comment by trevorstephens** [comment]
https://gplearn.readthedocs.io/en/stable/intro.html#transformer

"the absolute value of the correlation is maximized in order to accept strongly negatively correlated programs."
