### ISSUE TITLE
Optimal Population Size 

### ISSUE THREAD

**Issue by LACORTEZ33** [trevorstephens/gplearn#291]
For a relatively small datasets we are trying to find  y=f(x) 
We realized the results quality are highly dependent  on  the number of programs (population size).   
The optimal number of programs seems to be a function of number of data points and overall correlation between x and y. 
Any hint to define the optimal number of programs? 

Thanks

**Comment by trevorstephens** [comment]
Sorry but every problem is different and I cannot advise on individual datasets. There is general advice [in the docs](https://gplearn.readthedocs.io/en/stable/intro.html#initialization)
