### ISSUE TITLE
Allow nans in X

### ISSUE THREAD

**Issue by apexjmr** [trevorstephens/gplearn#298]
I would like to enable nans in X.  Is it possible to prevent this check?

**Comment by apexjmr** [comment]
In genetic.py, I have hard coded gplearn source to what I am hoping to have added as a parameter to gplearn:

fit: 
```
            X, y = self._validate_data(X, y, y_numeric=True, validate_separately=(
               dict(force_all_finite=False),
               dict(force_all_finite=True, ensure_2d=False),
            ))
```

transform:
```
           X = check_array(X, force_all_finite=False)
```

**Comment by trevorstephens** [comment]
tbh i dont see a lot of demand here. allowing NaN's in X would require all functions used in the evolution to handle them and currently all will propogate NA through to fitness evaluation.
