### ISSUE TITLE
100.000 file, ~1GB save files when saving model to disk.

### ISSUE THREAD

**Issue by hasakura511** [trevorstephens/gplearn#3]
Hi Again,

When I tried to save the model to disk using 

from sklearn.externals import joblib

it created ~100,000 6kb numpy files and one 42mb pickle file.

Please advise how to fix this.

Thank you.

**Comment by trevorstephens** [comment]
`joblib` saves each array in the object as a separate file. `gplearn` has an array for each program so it is not surprising that there are a lot of items pickled. You could pickle only the "best" program and then re-insert it into a new object if you don't care about the programs that it evolved from.
