### ISSUE TITLE
Include logic regression

### ISSUE THREAD

**Issue by trevorstephens** [trevorstephens/gplearn#32]
New estimator, needs much more research to see how/if it fits into `gplearn`'s API. No milestone yet. [Citation](http://kooperberg.fhcrc.org/logic/documents/logic-regression.pdf)

Add boolean/logical functions, conditional functions and potential to input a binary input dataset

**Comment by rspadim** [comment]
xor function is importnat for binary data

https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_xor.html

i couldn't create it with gplearn, any idea? how to do this?

from gplearn.functions import make_function
xor = make_function(function=np.logical_xor, name='mod', arity=2)

**Comment by trevorstephens** [comment]
Whenever I get around to implementing this class I will look to include XOR as an option. In the meantime if you need to implement your custom functions you would most likely need to add something along the lines of `x < 0` (ie. treat all negatives as False, positives as True) as arguments to the numpy functions in order to have the numpy logical functions work. `gplearn` currently will cast all input data to floating point during training, even if it's binary so you need to guard for that in any custom functions.

**Comment by LaGvidilo** [comment]
> xor function is importnat for binary data
> 
> https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_xor.html
> 
> i couldn't create it with gplearn, any idea? how to do this?
> 
> from gplearn.functions import make_function
> xor = make_function(function=np.logical_xor, name='mod', arity=2)

For exemple 
```
def xorB(a,b):
    return -b+a+np.float32(np.logical_xor(a,b))-a+b
```

And 
`xor1 = make_function(function=xorB, name='xor', arity=2)`

That help you ?
