### ISSUE TITLE
get best program with OOB score

### ISSUE THREAD

**Issue by rspadim** [trevorstephens/gplearn#34]
hi guys, how could i scan _programs and get the best OOB program?

**Comment by trevorstephens** [comment]
Looks like I missed documenting this. There is an attribute called `oob_fitness_` in each program that you can loop through to find the best one. I shall add this documentation in the next release.

**Comment by iblasi** [comment]
@rspadim, I posted a code in issue [#47](https://github.com/trevorstephens/gplearn/issues/47) that may show you how to extract all the best OOB of each program (not only the best one in case you need it) that may help you to extract the attribute called `oob_fitness_` that @trevorstephens was refering to.
