### ISSUE TITLE
fuzzy functions - and,xor,not,or

### ISSUE THREAD

**Issue by rspadim** [trevorstephens/gplearn#35]
hi guys, could you include fuzzy functions as default?

def fuzzy_not(x):
    return np.minimum(1,np.maximum(0,1-x))
def fuzzy_and(x,y):
    return np.minimum(1,np.maximum(0,x*y))
def fuzzy_or(x,y):
    return np.minimum(1,np.maximum(0,x+y/2))
def fuzzy_xor(x,y):
    return np.minimum(1,np.maximum(0,0.5 - 2 * (x - 0.5) * (y - 0.5)))

**Comment by trevorstephens** [comment]
As these are not straight-forward functions, and probably for a very constrained use-case, this looks like a perfect candidate for the user-defined functions #18 feature to be implemented by the user.
