### ISSUE TITLE
Add another fit API(for reinforcement learning use case)

### ISSUE THREAD

**Issue by eggachecat** [trevorstephens/gplearn#39]
Hi, @trevorstephens 
In my opinion, GP is different from other regression/fit algorithms since there can be no accurate target value for it to fit. You can simply train GP by telling it whether the result it generates is good or how good the result is, so GP is more like a reinforcement learning algorithm to me than a supervised learning algorithm(e.g. linear regression, LR, SVR...)

Considering this feature(reinforcement-use-case), I think the current fit(X,Y) API may not be enough(for supervised learning use case it still works fine)...

Although this can be done with the current set of APIs like this:

```python
def evaluation_function(y_pred):
     #do what you want
     return score

def explicit_fitness(y, y_pred, sample_weight):
    # normally we compare y_pred with y and get a score
    # but what about the case we dont know the accurate/target y?
    # in this case we just use y_pred to evaluate the performance 

    return evaluation_function(y_pred)

SymbolicRegressor(metric=make_fitness(explicit_fitness, False))

# in the case that we use only y_pred to evaluate the performance,
# y_data in fit(x_data,y_data) is useless

y_as_indices = [i for i in range(x_data.shape[0])]
est_gp.fit(x_data, y_as_indices)
```
I still look forwarding another API for this purpose...
In some case, may we use the x_data in the fitness function?
Thanks!!

**Comment by trevorstephens** [comment]
Currently the focus of the project is only on supervised learning problems. If the scope expands in the future I may consider such API expansion but this is out of scope for now @eggachecat
