### ISSUE TITLE
Add max_time_mins, which overrides generations and acts like stopping_criteria

### ISSUE THREAD

**Issue by sohrabtowfighi** [trevorstephens/gplearn#41]
It would be helpful if the code had a walltime, aka max_time_mins, that it enforced just like the stopping_criteria.

**Comment by trevorstephens** [comment]
Hi @sohrabtowfighi , thanks for the feedback but it feels a bit out of scope for this project. However, this could be easily implemented by the user by iterating over a `warm_start` and adding a new generation one at a time, and then stopping once your timer has reached whatever threshold you need. See http://gplearn.readthedocs.io/en/stable/advanced.html#continuing-evolution-with-warm-start for how to use.
