### ISSUE TITLE
Question on User-defined function

### ISSUE THREAD

**Issue by RameshArvind** [trevorstephens/gplearn#43]
Hi, So I've had a look at the custom functions definition. While constructing possible individuals from my code I ran into some issues.
```
pset = gp.PrimitiveSetTyped("MAIN",[int],str)

pset.addPrimitive(intprocessor,[int],list)
pset.addPrimitive(listprocessor,[list],str)
pset.renameArguments(ARG0='x')
```
the error I'm facing is this 
``IndexError: The gp.generate function tried to add a terminal of type '<type 'str'>', but there is none 
available``

Now one way of solving this issue is to use terminals as evident by the error message 
``pset.addTerminal("hello", str)
pset.addTerminal([123], list)
``
But when the terminals are not defined shouldn't the GP be only producing `listprocessor(intprocessor(x)) `since its the only tree which is possible ?

**Comment by trevorstephens** [comment]
Looks like you are referring to a different package?

**Comment by RameshArvind** [comment]
Oh wow. My bad I was going through a bunch of libraries. This was intended for something I'm trying out with deap at the moment. Gplearn I found out about just today. Will probably try what I'm planning to do on gplearn in sometime.
