### ISSUE TITLE
How to write custom function with make_function?

### ISSUE THREAD

**Issue by pchankh** [trevorstephens/gplearn#45]
I did the following and gotten errors:

from gplearn.functions import make_function

def internaltanh(x):
    return np.tanh(x1)

dtanh = make_function(function=internaltanh, name='dtanh',arity=1)

function_set2 = ['add', 'sub', 'mul', 'div', 'sqrt', 'log','dtanh', 'abs', 'neg', 'inv']
>>> gp2 = SymbolicTransformer(generations=20, population_size=5000,
...                          hall_of_fame=100, n_components=10,
...                          function_set=function_set2,
...                          parsimony_coefficient=0.0001,
...                          max_samples=0.9, verbose=1,
...                          random_state=0, n_jobs=3)
>>> gp2.fit(xtrain2, xtrain.y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gplearn/genetic.py", line 317, in fit
    '`function_set`.' % function)
ValueError: invalid function name dtanh found in `function_set`.

How can we fix this error? Can we have an example?

Thanks
Dr Patrick

**Comment by iblasi** [comment]
pchankh, as it is mentioned on the documentation on the "[Customizing Your Programs](https://gplearn.readthedocs.io/en/stable/advanced.html)" section, if you define a new function user-defined, you should add it to the "function_set" but without commas.
So you should write it as:
function_set2 = ['add', 'sub', 'mul', 'div', 'sqrt', 'log',dtanh, 'abs', 'neg', 'inv']

Also, I found that your function can give you an error, because you are returning "return np.tanh(x1)" instead of "return np.tanh(x)", as x1 is not an existing variable.

```
import numpy as np
from gplearn.genetic import SymbolicRegressor
from gplearn.functions import make_function

def internaltanh(x):
  return np.tanh(x)

X = np.random.randint(0,100,size=(100,3))
y = np.tanh(X[:, 0])

dtanh = make_function(function=internaltanh, name='dtanh',arity=1)
function_set = ['add', 'sub', 'mul', 'div', 'sqrt', 'log', dtanh, 'abs', 'neg', 'inv']
est_gp = SymbolicRegressor(population_size=5000,
                           generations=20, stopping_criteria=0.01,
                           function_set=function_set,
                           p_crossover=0.7, p_subtree_mutation=0.1,
                           p_hoist_mutation=0.05, p_point_mutation=0.1,
                           max_samples=0.9, verbose=1,
                           parsimony_coefficient=0.01, random_state=0)
est_gp.fit(X_train, y_train)
print 'Score: ', est_gp.score(X_test, y_test)
print est_gp._program
```

Returns a prefect answer
```
    |    Population Average   |             Best Individual              |
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0    10.71    2265616.12717        2              0.0              0.0     40.50s
Score:  1.0
dtanh(X0)
```

**Comment by trevorstephens** [comment]
Thank you @iblasi

**Comment by hgzhehe** [comment]
BTW,Does custom func support number arg?
I wrote


def _delay(ts,n):
    return np.append(np.array([0 for i in range(n)]), ts[:-n])


delay = make_function(function=_delay,
                      name='delay',
                      arity=2)

and got
raise ValueError('supplied function %s does not support arity of %d.'


Thanks
