### ISSUE TITLE
Some questions about using and future versions

### ISSUE THREAD

**Issue by nnnet** [trevorstephens/gplearn#46]
Hello!
If you allow, I will continue (https://github.com/trevorstephens/gplearn/issues/22) to ask questions in the hope that some of them will be implemented in the next versions.
1. In your opinion, is it best to create an _Function using eg sklearn.linear_model.LinearRegression or sklearn.neighbors.KneighborsClassifier?
And get access to the methods fit () and predict ()?
2. As a result of the work of SymbolicTransformer received a certain set of chromosomes.
How it is better to transform them into objects of type TransformerMixin for further use in piplines separately from SymbolicTransformer?
PS If in the next versions you will implement the transfer of parameters to the function, then it is probably better to do it as a dictionary with ranges, so that you can use eg HyperOpt

**Comment by trevorstephens** [comment]
Hi @nnnet 

1. Not sure that I understand what you are asking here?
2. See `test_pipeline()` in the test suite on how to implement into a `sklearn` pipeline https://github.com/trevorstephens/gplearn/blob/master/gplearn/tests/test_genetic.py#L786-L806 ... Is that what you are looking for? For more advanced use, see `FeatureUnion` at http://scikit-learn.org/stable/modules/pipeline.html
