### ISSUE TITLE
Is it possible to get the transformed features automatically？

### ISSUE THREAD

**Issue by olap1200** [trevorstephens/gplearn#55]
Hi, 

thanks for building this awesome package.

I am using it to do feature engineering, getting new features and use them to build more models. just wanna know if there is a way to get the transformed features automatically?

like, in the Symbolic Regressor example, we got the solutions by doing this：

```
print est_gp._program

sub(add(-0.999, X1), mul(sub(X1, X0), add(X0, X1)))
```
can we, instead of expanding the mathematics out manually, directly have the new feature names in a list or new dataframe of those new features? like:

```
.new_featrues_df 

[
  ['x0**2', '-x1**2', 'x1']
  [4, -1, 1]
  [25, -9, 3]
]

```
thanks!

**Comment by trevorstephens** [comment]
Hey there @olap1200 ... Too easy! The transformer is iterable, so just do:

    >>> for program in est_gp:
            print program

Is that what you were looking for?

**Comment by trevorstephens** [comment]
(That will give you the top x programs that met whatever hall of fame and desired components you were working with btw)

**Comment by trevorstephens** [comment]
Feel free to re-open if I missed your intention here...
