### ISSUE TITLE
module 'gplearn' has no attribute 'genetic'

### ISSUE THREAD

**Issue by Drxan** [trevorstephens/gplearn#56]
**code like this:**

1.     import gplearn
2.     est_gp = gplearn.genetic.SymbolicRegressor()

**But there is an error msg as follows:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-3d0a370a76f2> in <module>()
      1 import gplearn
----> 2 est_gp = gplearn.genetic.SymbolicRegressor()

AttributeError: module 'gplearn' has no attribute 'genetic'

my python version =3.6,anyone can help me?

**Comment by trevorstephens** [comment]
You need to import the genetic module or the estimator itself.

    from gplearn import genetic

or 

    from gplearn.genetic import SymbolicRegressor
