### ISSUE TITLE
scikit-learn contrib?

### ISSUE THREAD

**Issue by amueller** [trevorstephens/gplearn#57]
Hey Trevor.
Have you thought about the project becoming part of scikit-learn-contrib
https://github.com/scikit-learn-contrib/ ?
Right now the exact governance of that repo is still a bit in flux, but I think it does serve the purpose of advertising high-quality scikit-learn compatible models and extensions.

Andy

**Comment by trevorstephens** [comment]
I've been toying with the idea. Will keep an eye on the ecosystem there and whether it makes sense to transition over to `scikit-learn-contrib`. What governance is in flux @amueller ?

**Comment by amueller** [comment]
Well right now it's mostly sklearn core devs reviewing and making decisions, but I think we hope we'll get more of the contrib package contributors to help out.
