### ISSUE TITLE
Customized function takes forever to run for SymbolicTransformer

### ISSUE THREAD

**Issue by hubokitty** [trevorstephens/gplearn#63]
I just started to use this package. I was running the gp_examples.ipynb. Everything was fine except that it takes forever for SymbolicTransformer to run with user-defined logical function on my computer in Example 3. Is it normal?  

Thanks a lot for your help.

**Comment by trevorstephens** [comment]
No, that is not normal. Can you give me more details? 

- What does "take forever" mean?
- What version of gplearn are you running? 
- Are you running all the commands in the notebook sequentially without modification?

**Comment by trevorstephens** [comment]
Just released the new version, can you try again with the latest? Let me know more about your error/environment/etc?

**Comment by hubokitty** [comment]
Trevor, I tried the latest version and still have the same issue. Right now I use the default function set for now. I do have an extra question: I know gp._programs stores the symbolic expressions for each generation. Assume that I set population_size = 800, generations = 40, n_components = 20, and want to output the expressions of final results, shall I output gp._programs[39][0:19]?

Thank you so much for your patience.

**Comment by hubokitty** [comment]
Update: we tested the same code on Linux environment and the same user-defined function takes No time to run. The same code ran for days on Windows without generating even the first iteration. There's no error information either. It's indeed related to the environment.

**Comment by trevorstephens** [comment]
Thanks for the follow up @hubokitty ... I'll attempt to set up Appveyor to run tests on Windows to see if it can replicate the problem. 

Are you using a distribution like anaconda to install python and the numpy stack?

**Comment by trevorstephens** [comment]
`SymbolicTransformer` stores the final solutions in the attribute `_best_programs`. `_programs` contains all of the generations but it does not sort them so the `[0:19]` in your code will just get a random selection of the final generation.

**Comment by trevorstephens** [comment]
@hubokitty ... Tests are passing on Windows. I added a new test in #70 that performs the example in the docs with the logical function. It completes just fine on AppVeyor which runs on Anaconda in Windows.

The only difference I see that might be an issue for you is that that example uses the `n_jobs` attribute which invokes the `joblib` library. Can you try to run some other tests using joblib and see if that is the issue. If that is the case then the problem lies upstream of this package.

**Comment by hubokitty** [comment]
Trevor, thanks a lot for your reply. I saw you opened another issue related to this. I look forward to the solution.

As to final expressions, now I understand the generations are not sorted.  If I am indeed interested in the symbolic expressions of the final components selected (say top 20), how shall I obtain those expressions based on your program?
