### ISSUE TITLE
Image(graph.create()) problem with Example of GPLearn

### ISSUE THREAD

**Issue by jecs89** [trevorstephens/gplearn#64]
graph = pydotplus.graphviz.graph_from_dot_data(est_gp._program.export_graphviz())
print graph
Image(graph.create())

Error:
sub(add(-0.999, X1), mul(sub(X1, X0), add(X0, X1)))
<pydotplus.graphviz.Dot object at 0x7f3a3b2f56d0>
Traceback (most recent call last):
  File "test.py", line 83, in <module>
    Image(graph.create())
  File "/home/josimar/Envs/test/local/lib/python2.7/site-packages/pydotplus/graphviz.py", line 1960, in create
    'GraphViz\'s executables not found')
pydotplus.graphviz.InvocationException: GraphViz's executables not found

**Comment by trevorstephens** [comment]
As the error states, pydotplus cannot find your Graphviz installation. Suggest you see that project or 
try stackoverflow for assistance.

**Comment by jecs89** [comment]
I found a manual solution:
sudo apt-get install graphviz

graph.write('test.dot')
dot -Tps test.dot -o outfile.ps
