### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by rhiever** [trevorstephens/gplearn#65]
We're using gplearn in a research paper. Do you have a preferred citation for gplearn?

**Comment by trevorstephens** [comment]
No preferred citation @rhiever ... Happy to hear that you are using it in your research 👍 If you have a link to the paper I would be interested to read it at some point though. Cheers 🍻

**Comment by rhiever** [comment]
OK, we'll just link to the docs in the paper. I'll set a reminder to drop a link to the preprint when it's out. We used gplearn as a baseline representation of symbolic regression to compare our methods to. gplearn didn't do very well compared to XGBoost and our methods, although it did beat Lasso regression on most of the benchmark datasets when given enough population size & generations (1000x1000)

**Comment by trevorstephens** [comment]
Any update on this @rhiever ? Be interested to read how people are using the package in the wild :-)

**Comment by rhiever** [comment]
Paper isn't finished (fell off the table due to other priorities), but still in progress.

**Comment by trevorstephens** [comment]
@iandinwoodie feel free to point to the docs or the repo :smiley:
