### ISSUE TITLE
Possible to remove const_range?

### ISSUE THREAD

**Issue by xiaojunw** [trevorstephens/gplearn#66]
Hello,
I just started using this library. Could anyone help if it is possible to remove const_range? Since I would like to perform 'add,minus' methods only between variables.

I set const_range to (0,0). But got many of these expressions:
add(add(add(0.000, X0), 0.000), 0.000)

Thanks a lot.

**Comment by trevorstephens** [comment]
This is not currently supported. Your method will get the desired result, although with the potential for "dead branches" in the program trees.

I think it makes sense to put this on the roadmap for inclusion as an explicit feature though.
