### ISSUE TITLE
Run in parallel took much more time than single job

### ISSUE THREAD

**Issue by CookieMonsterYan** [trevorstephens/gplearn#71]
Hi,

I just started using gplearn.
When I run the symbolic regressor example with n_jobs = 1, it took about 5 minutes and finished. However, when I set n_jobs = 15, it was still running after one hour, and I had to stop it manually.

Here is my environment:
Windows 7 Professional,
Anaconda 3, 
CPU Xeon E5-2687w v2.

Could anyone help me? Thanks very much.

**Comment by trevorstephens** [comment]
Possibly related to #63 .. Are you running the examples from the documentation? Can you try to run the notebook in the repo and see if it fails to complete the custom function (logical operator) example as with the other bug report?

**Comment by CookieMonsterYan** [comment]
I tried the custom function example in the notebook. It took more than 10 minutes and dailed to complete. I also tried the n_jobs=1 in the custom function example, and this time it completed in less than 1 minute.

**Comment by trevorstephens** [comment]
Interesting, thanks for the feedback. I don't have a Windows machine myself for any deep testing, but the code is based of sklearn's RandomForest implementation of parallelization ... Have you ever run into issues with that package?

**Comment by CookieMonsterYan** [comment]
Hi, I tested the sklearn's RandomForest, and set n_jobs=10, it works.

**Comment by xuyaoGitHub** [comment]
Got the same question. Got the following error:
  File "C:\ProgramData\Anaconda3\Lib\multiprocessing\connection.py", line 251, i
n recv
    return _ForkingPickler.loads(buf.getbuffer())
AttributeError: Can't get attribute 'logic' on <module '__main__' (built-in)>

**Comment by eggachecat** [comment]
I think the main reason for this issue is python's poor support for serialization...
One way I come up with is to passing the formula(the string) through processes and construct the program from the string and it works.
As for the `RandomForest` case I think there's no function-type parameters need to be passed  through processes.

**Comment by trevorstephens** [comment]
It appears like the 'loki' backend for joblib may relieve this windows problem. Shall investigate for next release: https://joblib.readthedocs.io/en/latest/parallel.html#old-multiprocessing-backend

**Comment by trevorstephens** [comment]
joblib 0.12 uses 'loki' by default apparently, Aug 3, 2018 was when scikit-learn upgraded to this version which is after much of the activity on this thread. Need to stand up a Windows machine to test configurations. :-( Currently pegged to joblib >= 0.11 ... Might bump to 0.12 as a solution?

**Comment by trevorstephens** [comment]
@eggachecat ... Sorry, are you still following this? When you passed the formula as a string, do you mean like a literal formula representation that you parsed somehow? Or a pickled _Function class being passed as a pickle string?

**Comment by trevorstephens** [comment]
Just spun up a Windows image. Was able to reproduce the non responsive example. Upgrading to gplearn 0.4.0 solved the issue. Might be some related issues around documenting when you should do parallel processing due to the serial nature of the evolution process.
