### ISSUE TITLE
Avoid sub(x1,x1)

### ISSUE THREAD

**Issue by xuyaoGitHub** [trevorstephens/gplearn#72]
How to define customised function to avoid sub(x1,x1) in formula?
Thanks in advance for help.

**Comment by trevorstephens** [comment]
This is not currently supported or on the roadmap. Perhaps there is a way to reduce the formulas after fitting the model, but recursing every program looking for the miriad ways that a branch of the program tree could become redundant would probably be equally, or more, computationally expensive than the calculation of the program's output even with redundant branches.
