### ISSUE TITLE
save the best answer for next generation

### ISSUE THREAD

**Issue by nasergh** [trevorstephens/gplearn#78]
Hi
why GP forget the best answer 
Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0     5.37   0.119489734754       10    0.32867068184    0.32867068184     31.98m
   1     7.28   0.198452270512       10    0.32867068184    0.32867068184     34.04m
   2     9.77   0.232682978397       18    0.33828699039    0.33828699039     38.34m
   3    12.78    0.24580809457       16   0.354089304335   0.354089304335     41.70m
   4    10.61   0.250780473827       20   0.357985272035   0.357985272035     40.96m
   5     9.09   0.260635874919       19   0.360901882857   0.360901882857     37.68m
   6     7.41   0.271215266832        9   0.362093931344   0.362093931344     33.31m
   7     6.16    0.28317704956        9   0.364512346616   0.364512346616     28.76m
   8     5.89   0.290670160802       11   0.366410287748   0.366410287748     24.75m
   9     5.11   0.290512556887        9   0.373036949087   0.373036949087     21.30m
  10     6.29    0.28647044864        9   0.373174499224   0.373174499224     18.46m
  11     7.48   0.283990428547        9   0.374180221999   0.374180221999     16.00m
  12     7.65   0.280967975643        9   0.374180221999   0.374180221999     13.70m
  13     7.81   0.283605716579        9   0.374180221999   0.374180221999     11.51m
  14     7.78   0.288654964337        9   0.374180221999   0.374180221999      9.41m
  15     6.67   0.293166086785        9   0.374180221999   0.374180221999      7.34m
  16     6.18   0.311366081447        9   0.374180221999   0.374180221999      5.35m
  17     6.27   0.314700474039        9   0.373310184007   0.373310184007      3.47m
  18     6.15   0.315235710354        9   0.372597445771   0.372597445771      1.69m
  19     5.16   0.306663647911        7   0.369576641621   0.369576641621      0.00s
best answer(correlation was the fitness) in run 18 was 0.37 but in run 19 best answer is 0.36
Gp must save the best answer(elitism)
how i can do that ?
2- how i can access to all population in final solution ?
thanks

**Comment by trevorstephens** [comment]
Thx @eggachecat for your tips! Exactly right, not all programs will get into the tournaments. And if they do, they will likely be modified by one of the mutation or cross-over mechanisms, and their children's fitness isn't guaranteed to be better. `est._programs` contains all of the generations in a list of lists structure. These aren't public attributes but you can tool around there as much as you like.

Another point is that bootstrapping your samples might change these results generation to generation even if the result is the same! If you OOB sample size fluctuates a lot then your solution may be overfit. Might be worth upping the parsimony if that is the case. Or get more data :-)

Another way to increase the likelihood of a superior program getting through evolution unchanged is to reduce the probabilities of some of the cross-over or mutation actions. The remaining probability goes to "reproduction" which means simply cloning the winner of a tournament into the next generation.

**Comment by nasergh** [comment]
Hi
if population size = 5000 then tournament size = ? to save the best fitness ?
i think you need to add elitism to your code to save the best answer in each population and give it to next generation.

**Comment by trevorstephens** [comment]
See my last paragraph above. If you reduce the amount of mutation/crossover the balance goes to reproduction. That is "elitism", at least within the tournament.

**Comment by nasergh** [comment]
if i reduce the mutation/cross over then it's mean i reduce the exploration and ... of algorithm
mutation use for big jump in feature space 

pls tell me  good setting for mutation / cross over percentage

**Comment by nasergh** [comment]
if i reduce the mutation/cross over then it's mean i reduce the exploration and ... of algorithm
mutation use for big jump in feature space
i use default setting but as you can see GP can't minimize the fitness
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0     5.25     662401.03707        3 1.42914053171e-05 1.42914053171e-05     54.23s
   1     2.02    64800.1593379        3 0.00112163694402 0.00112163694402     31.61s
   2     3.58    86400.0575746        4 0.000560818472011 0.000560818472011     23.67s
   3     1.27    27000.0143403        2 0.00187837350028 0.00187837350028     10.35s
   4     1.02    3600.01189834        1 0.00375674700055 0.00375674700055      0.00s

pls tell me good setting for mutation / cross over percentage

**Comment by trevorstephens** [comment]
You either reduce exploration or increase the likelihood of cloning a program into the next generation. You can't have it both ways. 

Default settings are a "good start" but optimal ones depend on the problem and that is up to the user to discover themselves through experimentation or some sort of exhaustive grid-search.
