### ISSUE TITLE
bug in fitness function

### ISSUE THREAD

**Issue by nasergh** [trevorstephens/gplearn#79]
Hi
i run the GP with custom fitness = correlation
but after some run suddenly it give 100% correlation !!! and when i evaluate the answer it's give 0.001 correlation !
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0     5.54  0.0507770546032        4   0.250331869604   0.250331869604     39.48m
   1     5.29    0.17578891758        8   0.292678918784   0.292678918784     36.42m
   2     6.31   0.195609863013       15   0.309292306233   0.309292306233     37.17m
   3     7.49    0.21727944686       18   0.309676574428   0.309676574428     37.30m
   4     4.61   0.215170121463       10    0.30670011254    0.30670011254     36.45m
   5     4.92   0.220007718385        8   0.307863858177   0.307863858177     34.56m
   6     2.82   0.204527539158        5   0.296555470942   0.296555470942     31.32m
   7     4.61    0.21882486821        6   0.303621894897   0.303621894897     29.67m
   8     3.43   0.207376271839        6   0.303670264738   0.303670264738     26.44m
   9     4.95    0.22855497256        6   0.303947856067   0.303947856067     24.20m
  10     1.88   0.196746932658        7   0.303625011651   0.303625011651     20.95m
  11     5.24   0.227187099229        8   0.306198502413   0.306198502413     18.94m
  12     4.41   0.220586196802        6   0.303947856067   0.303947856067     16.53m
  13     2.14   0.218803874449        6   0.247317332288   0.247317332288     13.58m
  14     4.92   0.177533556647        8    0.26462889826    0.26462889826     11.14m
  15    11.43   0.166718597989       20   0.295949290086   0.295949290086      9.17m
  16     5.83   0.186450562698       22   0.293827088491   0.293827088491      6.72m
  17     5.38   0.204843829724        8   0.301037286507   0.301037286507      4.41m
  18     4.51   0.211492379156        8   0.303106229866   0.303106229866      2.17m
  19     2.17   0.217744236103        6              1.0              1.0      0.00s

def _corr(y_pred,y, w):
    y=np.where(np.isnan(y), 0,y)
    y=np.where(np.isinf(y), 0,y)
    y1=pd.DataFrame(y)
    y2=pd.DataFrame(y_pred)
    
    c=y2[0].corr(y1[0])
    if(np.isnan(c) or np.isinf(c)):  
        c=0
    return (abs(c))

     
cor = make_fitness(_corr, greater_is_better=True)
    
est_gp = SymbolicRegressor(population_size=5000,function_set=function_set,
                           generations=20, tournament_size=100,
                           p_crossover=0.7, p_subtree_mutation=0.1,verbose=1,
                           p_hoist_mutation=0.05, p_point_mutation=0.1,max_samples=0.9,
                           const_range=(-1,20),stopping_criteria=0.95,
                           parsimony_coefficient='auto',
                           metric=cor)

**Comment by trevorstephens** [comment]
Without a reproducible example I can't debug this to see if this is a problem with gplearn, or a problem with your fitness function.

You could try to use the `_weighted_pearson` fitness function from `gplearn.fitness` if you wanted to see if the problem persists with a different metric formulation.

**Comment by trevorstephens** [comment]
I guess that solved the problem. I just raised an issue to include correlation as a first-class metric for the regressor, so closing for now and stay tuned for less work by the user for a popular use-case. :-)
