### ISSUE TITLE
Bug report about custom function

### ISSUE THREAD

**Issue by zodiac911** [trevorstephens/gplearn#83]
in your gp_examples notebook, you demonstrated a way to create custom defined functions

But when  I run the test,  the function can only work when the regression or transformer's `n_jobs` parameter set as 1 or None, if `n_jobs` was set to 2 or 3 etc it won't work and error 
`AttributeError: Can't get attribute '_logic' on <module '__main__' (built-in)>`
was reported

Maybe a bug?

**Comment by trevorstephens** [comment]
This does seem to come up a bit @zodiac911, you are not the first ... I have automated tests running on linux and windows at each PR that all pass. I have not run into the problem myself and so cannot really debug it :-(

Can you give some details on the OS, python build, etc?

**Comment by zodiac911** [comment]
@trevorstephens I think the reason is Windows, after I switched to Ubuntu the problem was gone. Maybe it's the bad support of multiprocessing on Windows.

**Comment by trevorstephens** [comment]
Thanks for the reply @zodiac911 :-) I've been trying to squash all the bugs I find over the years (in whatever free time I can spare), but Windows seems to be the hardest one. I'll keep at it and maybe spin up a Windows machine on an old laptop to help with that. No promises! Glad to hear that you sorted out that issue but also glad to know it exists for others. Thanks for the report. :+1:
