### ISSUE TITLE
Models as nodes

### ISSUE THREAD

**Issue by echo66** [trevorstephens/gplearn#84]
Greetings!

Instead of having stateless nodes, we could have nodes that are models themselves. That would require 
us to create a program "training" phase in gplearn, correct?

**Comment by trevorstephens** [comment]
Given that the inputs are potentially arbitrary; ie. each node's dependencies might be mutated such that the next generation's input features will be completely different, I don't see how this would be beneficial. It doesn't feel like a good fit to `gplearn` at first glance. Can you expand on your idea?

**Comment by echo66** [comment]
If you take a look at what things like TPOT do, you see where I'm coming from. In TPOT, each node is a transformer or estimator. TPOT uses DEAP.

**Comment by trevorstephens** [comment]
TPOT is something completely different to the aims of this project. TPOT is a hyperparameter optimiser that uses genetic algos as its optimiser... gplearn is a machine learning algorithm that uses genetic programming as its engine for machine learning, I might consider somethign akin to this in the future but currently feels very much out of scope.
