### ISSUE TITLE
Capture details of a run into a log file

### ISSUE THREAD

**Issue by bartolkaruza** [trevorstephens/gplearn#86]
I may have missed this, but I could not find anywhere in the documentation how to get the structured output of a gp run into a text file. Currently they are printed like this:
```
    |    Population Average   |             Best Individual              |
---- ------------------------- ------------------------------------------ ----------
 Gen   Length          Fitness   Length          Fitness      OOB Fitness  Time Left
   0     7.45 3.884057507196499        4 0.8595262907809801              N/A     25.34m
....
```
with `verbose=1,` setting. 

From the printed log, I currently use Sublime Text multi-column select to extract individual column data for each generation, and use that to create descriptive charts like this one:
![tree_depth_mase_comparison](https://user-images.githubusercontent.com/1605731/42731622-299d76b2-8811-11e8-84bb-e36474cf5abc.png)

This is a lot of manual hassle, and very error prone as the columns are not nicely aligned. Is there some way to have gplearn output the details of the run to CSV or some other structured file format instead? If not, I would be happy to contribute a PR if you could point me in the right direction.

**Comment by trevorstephens** [comment]
That's a great idea! (yes, currently not supported) Will think on the best way to do this, but what kinds of metrics would you want to see in an output? Just the same stuff as seen in the verbose reporter? ... Or more?

**Comment by bartolkaruza** [comment]
One additional metric that would be very useful is the generations actual runtime, as I'm seeing a big increase over time that seems to not directly correlate to population average individual size. Some more technical metrics like per generation memory usage increase/total might help as well in finding bottlenecks.

Just the current metrics would be a huge win already.

**Comment by trevorstephens** [comment]
Would you want to also save things like the depth/length/fitness of each member in the generation @bartolkaruza ? ie. so you could calculate arbitrary metrics on your own? This seems like an easy thing to add in that would allow users to "self-serve".

**Comment by bartolkaruza** [comment]
That would be a great addition as well. My concern is that if you keep that data in the estimator object, the size of the object will grow massively. I'm having trouble with memory on large EC2 instances (16GB memory and more) with 1000 individuals and more than 500 generations causing out of memory exceptions. If you add a lot of detail to each individual this memory usage will grow, but perhaps if the data is streamed to a file during the run, this is not a problem.

Being able to calculate these metrics for the whole population and for individuals will help a lot in understanding the distribution of each generation.
