### ISSUE TITLE
New node type: Variable

### ISSUE THREAD

**Issue by echo66** [trevorstephens/gplearn#88]
Instead of inserting arbitrary constants, add "variable" nodes that will act as coefficients in your program. You can optimize those coefficients using things like the [L-BFGS-B algorithm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html). AFAIK, this is what William Lacava does in [feat](https://github.com/lacava/feat).

**Comment by trevorstephens** [comment]
It doesn't really fit into the current API, but maybe in future versions.
