### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by bartolkaruza** [trevorstephens/gplearn#89]
As mentioned in #86 the memory usage of the estimator grows linearly, never decreasing. This seems to be caused by the full history of all individuals being held by the SymbolicRegressor instance.

The result is that long runs (many generations), bloated runs (individuals with many nodes) and wide runs (high population size) cause the program to stall. 

<img width="754" alt="screen shot 2018-07-22 at 15 56 51" src="https://user-images.githubusercontent.com/1605731/43046393-816660ea-8dc8-11e8-9a04-88622261a207.png">
  
Above image is of a ml.c5.4xlarge EC2 instance running in SageMaker. With the below logs showing the last generation that was succesfully trained:

<img width="986" alt="screen shot 2018-07-22 at 16 03 19" src="https://user-images.githubusercontent.com/1605731/43046417-d3b5716a-8dc8-11e8-8180-05a068ced22e.png">

One possible solution to this problem would be to write all completed generations, except for the last one, to disk and to not reference the older generations in memory. If no output file is specified, the reference could be dropped entirely, with a clear note in the documentation for anyone looking for that particular historical information.

**Comment by echo66** [comment]
I faced the same issue. I only noticed after I completed the benchmark procedures and tried to submit the serialized pipeline to a git repo.

**Comment by bartolkaruza** [comment]
I've tried to resolve this issue with a new parameter at #92.
