### ISSUE TITLE
GP  Hyperparameters

### ISSUE THREAD

**Issue by pGit1** [trevorstephens/gplearn#9]
Hi Trevor this package is simply AMAZING. Great compliment to my research for sure. 
Quick question: There are  a lot of tuneable parameters (this is a good thing) for both the symbolic regressor and symbolic transformer. In your experience how sensitive are the fitness measures to these parameters? Which ones typically have the biggest output on fitness performance (which key parameters should one focus tuning efforts on )? 

Sorry for the dumb question!

**Comment by trevorstephens** [comment]
Hi @pGit1 , thanks for the kind words. It is difficult to have a one size fits all answer to this question unfortunately. But in general, population size, tournament size and parsimony are going to have a great effect on the size and fitness of the programs. Getting the balance right takes a lot of trial and error. I would generally start with fewer generations and see how the fitness is evolving while trying different tournament sizes and parsimony coeffs. Then maybe reign in the parsimony a bit and let it grow slower over more generations to get a better fit.

If your research is academic, please consider a citation should a publication arise :+1:

**Comment by trevorstephens** [comment]
Oh and if you have not already, be sure to read through the docs where I try to describe the impacts of all the parameters... http://gplearn.readthedocs.org/en/latest/index.html

**Comment by pGit1** [comment]
Thanks Trveor! If a publication ever did arise I would DEFINITELY cite you
and this awesome package (my experiments have to stop failing first LOL)!
Thanks for your help! Interestingly, I was wondering whether you would
point me to the crossover and mutation parameters but your advice makes
perfect sense.

Appreciate the response!
