### ISSUE TITLE
Highly correlated features

### ISSUE THREAD

**Issue by echo66** [trevorstephens/gplearn#90]
Greetings!

When I use SymbolicTransformer, almost all features I create end up being highly correlated. I'm using SymbolicTransformer to produce features for a classifier. As such, I changed the fitness function to:
```python
def auc(y, y_pred, sample_weight):
    try:
        a = roc_auc_score(y, y_pred, sample_weight=sample_weight)
        return a
    except:
        return 0.5
```
Is this a known bug? Or am I doing something wrong?

I'm using release 0.3.0.

EDIT 1: I noticed that [PR 60](https://github.com/trevorstephens/gplearn/pull/60) checks for correlated individuals. If that is the case, why I'm still getting almost all programs returning highly correlated outputs with each other?

EDIT 2: 
These are the parameters I used in gplearn

```python
def _logical(x1, x2, x3, x4):
    return np.where(x1 > x2, x3, x4)


def get_gplearn_params(): 
    logical = make_function(function=_logical,
                            name='logical',
                            arity=4)

    function_set = ('add', 'sub', 'mul', 'div', 
                    'sqrt', 'log', 'abs', 'neg', 
                    'inv', 'max', 'min', 'sin', 
                    'cos', 'tan', logical)

    general_gp_params = {
        'population_size':1000, 
        'hall_of_fame':100, 
        'n_components': 2, 
        'generations':50, 
        'tournament_size':2, 
        'stopping_criteria':1.0, 
        'const_range':(-1.0, 1.0), 
        'init_depth':(2, 6), 
        'init_method':'half and half', 
        'function_set':function_set, 
        'parsimony_coefficient':"auto", 
        'max_samples':1.0, 
        'warm_start':False, 
        'n_jobs':1, 
        'verbose':0, 
        'random_state':10
    }
    
    return general_gp_params
```

**Comment by dontdrinkandcode** [comment]
Hello,

I'm having a similar experience, and thought I'd share with you what I've been doing to improve the diversity of my features. Apologies if you are well-versed in genetic programming - I'm very much an amateur trying to work things out.

Increase population size

Decrease tournament size (yours already looks low)

Decrease the number of generations (I watch the output for when the best individual fitness starts to stay them same)

Set a low parsimony coefficient (I find that auto can lead to rapid convergence to small and similar functions in the data I am using it on)


There is probably more to be done with changing the mutation probabilities and max_samples parameter, but the impression I get is that  there's a bit of trial and error required for each new set of data.

Hope this helps. It would be really great if a GP expert would write a beginners troubleshooting guide.

**Comment by trevorstephens** [comment]
Sounds like the same suggestions I would give @dontdrinkandcode , thanks!
