### ISSUE TITLE
Wanna change the order of the algorithm?

### ISSUE THREAD

**Issue by DkwingS** [trevorstephens/gplearn#91]
Greetings!
To begin with, gplearn is of great use to me as I'm working on a project using GP. However, I think the genetic programming in this project a little bit of simple. Usually, each iteration in GP is based on a series of selection, crossover, and mutation. I am just wondering what if the order of it could be changed (e.g., selection->mutation->crossover, or crossover-> selection-> mutation. etc.)? It would be great if users could manually define such processes!

**Comment by DkwingS** [comment]
I'm sorry if my descriptions are confusing. I'm just wondering whether the mutation process always happen before the selection process in gplearn? If so, is there a way to let the selection process happen after mutation process? Also, there are several genetic operations done through the mutation process, are they happened in specified order?

**Comment by bartolkaruza** [comment]
@DkwingS each individual in the next generation has only one of the transformations applied or no transformation. You can control which percentage of the total is generated using each of these techniques, with the `p_crossover`, `p_subtree_mutation`, `p_hoist_mutation` and `p_point_mutation` parameters. They should total less than 1, as stated in the docs:
```
Note : The above genetic operation probabilities must sum to less than one. The balance of probability is assigned to ‘reproduction’, where a tournament winner is cloned and enters the next generation unmodified.
``` 
http://gplearn.readthedocs.io/en/stable/reference.html#symbolic-regressor

What value is there in applying more than one transformation in 1 generation? Considering you can always just run more generations, that sounds redundant to me.

**Comment by DkwingS** [comment]
Really appreciate your help @bartolkaruza ! Your reply completely solves my confusion and helps me with one crucial problem that I'm currently working on:) .And I believe that's all for this issue. Thank you for all your helps!
